### ISSUE TITLE
Home Screen editing

### ISSUE THREAD

**Issue by saud-kh** [AniketMalik/ecommerce-store-support#1]
Is there any documentation on how to edit the Home Screen? 

the only thing I was able to find was the text at the top of the bar that says 'welcome to..'

How do I recreate the demo app Home Screen?

How to edit the splash screen?

How to disable onboarding all together?

**Comment by AniketMalik** [comment]
The home screen is dynamic and is based on the sections that you create in the WordPress dashboard. After you have followed the setup guide, you will be able to create sections from the WordPress dashboard. Rearranging them will change the layout of the home screen.

The splash screen can be edited from the splash.dart file under the screens directory.

As of now there is not a flag that you can change to disable this feature, however you can achieve this by changing the code in the splash.dart screen which pushes the navigator to onboarding screen.
