### ISSUE TITLE
Variable product price & image fetch error

### ISSUE THREAD

**Issue by herschalle** [AniketMalik/ecommerce-store-support#10]
Hello,

I have bought WooStore Pro today and I am using the app for my site and it has variable products having color as an attribute. In the app it shows all the correct color attributes but it fails to fetch price for such variable product and also the variation images. When I click on the variation color it does not show that variation image.

Also it shows product Out Of Stock where as it is in stock.

See attached image.

![variable product issue](https://user-images.githubusercontent.com/83502919/116783907-fe280880-aaae-11eb-8173-4a788da21177.jpg)

**Comment by AniketMalik** [comment]
Please share the log file of the same for me to understand the issue properly.

Also please set the color values of the color attribute using the data present in woostore_pro / lib / constants / colors.dart.

The application handles the color information using those values.

Please make the above mentioned changes and let me know. This should fix your issue.

**Comment by AniketMalik** [comment]
Please let me know if the issue was resolved after performing the steps mentioned above.

**Comment by herschalle** [comment]
Hello Aniket,

I tried but still getting same error. please find the entire log below



Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:51122/UcyG6K_L5Zk=/ws
Syncing files to device Android SDK built for x86...
I/om.azeao.avant( 6736): Background concurrent copying GC freed 16875(725KB) AllocSpace objects, 9(712KB) LOS objects, 49% free, 2817KB/5635KB, paused 5.387ms total 88.534ms
D/EGL_emulation( 6736): eglMakeCurrent: 0xf797f100: ver 2 0 (tinfo 0xe0cc1830)
I/FLTFireBGExecutor( 6736): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
D/EGL_emulation( 6736): eglCreateContext: 0xe41019e0: maj 2 min 0 rcv 2
D/EGL_emulation( 6736): eglCreateContext: 0xece74d20: maj 2 min 0 rcv 2
D/HostConnection( 6736): HostConnection::get() New Host Connection established 0xcc699450, tid 6849
D/HostConnection( 6736): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
D/EGL_emulation( 6736): eglMakeCurrent: 0xece74d20: ver 2 0 (tinfo 0xe0cf8d40)
I/FLTFireMsgService( 6736): FlutterFirebaseMessagingBackgroundService started!
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> isCustomerLoggedIn ==> AuthController ==> authController.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> _init ==> CoCart ==> coCart.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Setting key: null
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Setting cookie: null
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> _init ==> CoCart ==> coCart.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Is Logged in - false
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> isCustomerLoggedIn ==> AuthController ==> authController.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 [ Initiating for CategoriesProvider ] initState ==> ViewStateController ==> viewStateController.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 [ Initiating Type: HomeViewModel ] initState ==> SliverViewStateController ==> viewStateController.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> getCart ==> CartProvider ==> cartProvider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> getCategories ==> TestWooService ==> Woocommerce.service
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> fetchSections ==> HomeViewModel ==> homeViewModel.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> setCartKey ==> CoCart ==> coCart.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Headers are not null, setting cart key from headers
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> setCartKey ==> CoCart ==> coCart.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> setCartCookie ==> CoCart ==> coCart.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Setting cookie value from headers
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 set-cookie header list value is not null, processing...
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Headers' set-cookie for coCart is null, returning
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> getCategories ==> TestWooService ==> Woocommerce.service
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):    INFO ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):    INFO │ 💡 Got data with length: 0
I/flutter ( 6736):    INFO └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> fetchSections ==> HomeViewModel ==> homeViewModel.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 [ Initiating for SearchViewModel ] initState ==> ViewStateController ==> viewStateController.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
W/IInputConnectionWrapper( 6736): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6736): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6736): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6736): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6736): endBatchEdit on inactive InputConnection
W/om.azeao.avant( 6736): Reducing the number of considered missed Gc histogram windows from 158 to 100
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> fetchData ==> SearchViewModel ==> searchProvider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> _processRawData ==> SearchViewModel ==> searchProvider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> _processRawData ==> SearchViewModel ==> searchProvider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> fetchData ==> SearchViewModel ==> searchProvider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
W/om.azeao.avant( 6736): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/om.azeao.avant( 6736): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/om.azeao.avant( 6736): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/om.azeao.avant( 6736): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> fetchProductVariations ==> ProductViewModel ==> productViewModel.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> _getProductVariation ==> ProductViewModel ==> productViewModel.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):    INFO ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):    INFO │ 💡 Finding Product variation with variationId: 6083
I/flutter ( 6736):    INFO └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR │ NoSuchMethodError: The method '&' was called on null.
I/flutter ( 6736):   ERROR │ Receiver: null
I/flutter ( 6736):   ERROR │ Tried calling: &(4294967295)
I/flutter ( 6736):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6736):   ERROR │ #0   Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
I/flutter ( 6736):   ERROR │ #1   new Color (dart:ui/painting.dart:121:42)
I/flutter ( 6736):   ERROR │ #2   new HexColor (package:woostore_pro/utils/colors.utils.dart:16:37)
I/flutter ( 6736):   ERROR │ #3   ProductViewModel._getProductVariation.<anonymous closure> (package:woostore_pro/screens/product/viewModel/productViewModel.dart:333:13)
I/flutter ( 6736):   ERROR │ #4   ListMixin.firstWhere (dart:collection/list.dart:161:15)
I/flutter ( 6736):   ERROR │ #5   ProductViewModel._getProductVariation (package:woostore_pro/screens/product/viewModel/productViewModel.dart:296:27)
I/flutter ( 6736):   ERROR │ #6   ProductViewModel.setVariation (package:woostore_pro/screens/product/viewModel/productViewModel.dart:369:15)
I/flutter ( 6736):   ERROR │ #7   ProductViewModel.fetchProductVariations (package:woostore_pro/screens/product/viewModel/productViewModel.dart:137:7)
I/flutter ( 6736):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6736):   ERROR │ ⛔ Fetch error
I/flutter ( 6736):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 Running ==> fetchProductsById ==> ProductsProvider ==> products.provider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl( 6736): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter ( 6736):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR │ NoSuchMethodError: The method '&' was called on null.
I/flutter ( 6736):   ERROR │ Receiver: null
I/flutter ( 6736):   ERROR │ Tried calling: &(4294967295)
I/flutter ( 6736):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6736):   ERROR │ ⛔ 
I/flutter ( 6736):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR │ NoSuchMethodError: The method '&' was called on null.
I/flutter ( 6736):   ERROR │ Receiver: null
I/flutter ( 6736):   ERROR │ Tried calling: &(4294967295)
I/flutter ( 6736):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6736):   ERROR │ ⛔ 
I/flutter ( 6736):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   ERROR │ NoSuchMethodError: The method '&' was called on null.
I/flutter ( 6736):   ERROR │ Receiver: null
I/flutter ( 6736):   ERROR │ Tried calling: &(4294967295)
I/flutter ( 6736):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6736):   ERROR │ ⛔ 
I/flutter ( 6736):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6736):   DEBUG │ 🐛 End ==> fetchProductsById ==> ProductsProvider ==> products.provider.dart
I/flutter ( 6736):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by AniketMalik** [comment]
Hello, please share your wordpress url, consumer secret and consumer key you entered in wooConfig.dart file in your application via email at aniketmalikwork@gmail.com to me for testing. I'll check the application with your products on my end.

Please let me know the color values that you are using on this product variations.

Thank you.

**Comment by AniketMalik** [comment]
Found a possible issue.

While debugging I found that you are using a color which is not present in the color.dart file.
The first error causing color found was "light orange".

This color is not found in the lib/constants/colors.dart file which is why the application is not able to find the color and results in an error.

The possible solutions:

1. Add the colors you use in your products in the lib/constants/colors.dart file with their HEX values as there are other colors in the file. Please make sure that there is no space between the names of the colors as the application removes any space from the color names while searching for them. 

For example:  You should add "lightorange" instead of "light orange" in the lib/constants/colors.dart file and then use the same color in the product attribute as well.

2. You can use the names of the colors mentioned in the lib/constants/colors.dart file as there are many colors which can represent the colors you would like to show in your variable products.


Please perform the above steps and the issue will be resolved.
Please update me once done.

**Comment by AniketMalik** [comment]
Fixed in version v1.6.0
