### ISSUE TITLE
CoCart Error on logged in user

### ISSUE THREAD

**Issue by angelolaris** [AniketMalik/ecommerce-store-support#12]
Hello Aniket,

I am very happy with the progress I have made with you Woostore Pro Product.

I do however would like to get some assistance

I am getting the following error when accessing and or refresshing the cart. Can you assist me in resolving this issue?

The user is logged in using Google Login

Is there any reason why you did not use the woocommerce sdk

https://github.com/RayOkaah/woocommerce

I have found other errors which I have fixed and hope for more assistance

Thanks in advance

I/flutter ( 6097):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6097):   ERROR │ CoCartException{code: 403, status: null, message: null}
I/flutter ( 6097):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6097):   ERROR │ ⛔ Get Cart CoCartException
I/flutter ( 6097):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by AniketMalik** [comment]
The error is caused by CoCart Lite's latest version as it has some breaking changes. Please follow the below steps.

1. Download the compatible version from the following link: https://aniketmalik.github.io/woostore_pro_documentation/wordpress-setup/install-plugins#3-cart-rest-api-for-woocommerce--cocart-lite

2. Deactivate and delete the CoCart Lite 3.x.x version.
3. Install the downloaded version and activate it.

Thank you for your positive response. Please give me a good review on codecanyon if you like the application.

**Comment by AniketMalik** [comment]
The error is caused by CoCart Lite's latest version as it has some breaking
changes. Please follow the below steps.

   1.

   Download the compatible version from the following link:
   https://aniketmalik.github.io/woostore_pro_documentation/wordpress-setup/install-plugins#3-cart-rest-api-for-woocommerce--cocart-lite
   2.

   Deactivate and delete the CoCart Lite 3.x.x version.
   3.

   Install the downloaded version and activate it.

Thank you for your positive response. Please give me a good review on
codecanyon if you like the application.

The application uses an extended version of WooCommerce sdk as it lacked
various features to support the custom woostore pro api wordpress plugin.

**Comment by gaurav-netscapelabs** [comment]
![image](https://user-images.githubusercontent.com/75060994/132686209-c20859db-82eb-4ee7-b627-cd65e7e7d94b.png)
i have the cocart lite with version 2.9.3

but when I try to add the product to the cart from the application it returns...

`CoCartException{code: 403, status: cocart_cannot_be_purchased, message: Sorry, this product cannot be purchased.}`

Have a look on attached image


![image](https://user-images.githubusercontent.com/75060994/132686511-1f865764-fe0c-461f-a522-360c1996310b.png)

Please help to get it Done 
thanks in advance @AniketMalik

**Comment by AniketMalik** [comment]
Please check that the product is in stock and all other settings are
correct.

**Comment by gaurav-netscapelabs** [comment]
Yes the product is in stock plus I am able to add the product into the cart from the website but when I was trying to add it from a mobile it shows the _item added succesfully._ but in console, it shows an error just like I have attached

![image](https://user-images.githubusercontent.com/75060994/132836498-7cefee72-e90e-46d0-bfb9-5b90dbb5124c.png)
Regarding setting I have done all settings that have been mentioned on the document, anyhow If you can help to get it done will be valuable.
thanks in advance @AniketMalik

**Comment by AniketMalik** [comment]
Please check if the setting for *sold individually *is disabled as if you
already have the item in the cart from the website and you try to add it
again from the mobile application then it won't be added.

Does this happen only to 1 specific product or all the products ?

The source code has been checked again and we could not find any invalid or
unwanted behaviour in the testing. The error here is thrown only when the
product item flag *is_purchaseable *is set to false in the product setting
dashboard. Please checkout the WooCommerce Product Documentation for more
information. If you use any other plugin which manipulates the
product settings then please check that too if that is modifying the
product status.

Have a great time.

Regards,
Aniket Malik

**Comment by AniketMalik** [comment]
Please check if the setting for *sold individually *is disabled as if you
already have the item in the cart from the website and you try to add it
again from the mobile application then it won't be added.

Does this happen only to 1 specific product or all the products ?

The source code has been checked again and we could not find any invalid or
unwanted behaviour in the testing. The error here is thrown only when the
product item flag **is_purchaseable** is set to false in the product setting
dashboard. Please checkout the WooCommerce Product Documentation for more
information. If you use any other plugin which manipulates the
product settings then please check that too if that is modifying the
product status.

Have a great time.

Regards,
Aniket Malik

**Comment by AniketMalik** [comment]
Please let me know which version of the application, woostore pro api plugin are you using ?

**Comment by gaurav-netscapelabs** [comment]
![image](https://user-images.githubusercontent.com/75060994/132841133-89d96f75-04f1-413a-8368-41c708a7eb7a.png)
![image](https://user-images.githubusercontent.com/75060994/132841256-7f13d992-a7a1-40c6-9b5f-f9027c45b547.png)
![image](https://user-images.githubusercontent.com/75060994/132841302-e63509c6-f07a-4338-a86a-b9139aae0f78.png)
Rest let me know if you need more information on it.

**Comment by AniketMalik** [comment]
> Please check if the setting for *sold individually *is disabled as if you
> already have the item in the cart from the website and you try to add it
> again from the mobile application then it won't be added.
> 
> Does this happen only to 1 specific product or all the products ?
> 
> The source code has been checked again and we could not find any invalid or
> unwanted behaviour in the testing. The error here is thrown only when the
> product item flag **is_purchaseable** is set to false in the product setting
> dashboard. Please checkout the WooCommerce Product Documentation for more
> information. If you use any other plugin which manipulates the
> product settings then please check that too if that is modifying the
> product status.
> 
> Have a great time.
> 
> Regards,
> Aniket Malik

Please check this and answer the questions put forth in the comment above. Thank you.

Also please let me know if you have deleted the CoCart lite plugin from your WordPress installation.

**Comment by gaurav-netscapelabs** [comment]
_Also please let me know if you have deleted the CoCart lite plugin from your WordPress installation._
Do we need to delete that plugin 
![image](https://user-images.githubusercontent.com/75060994/132842327-28613802-80b8-4a80-abea-601705290d28.png)

**Comment by AniketMalik** [comment]
Please checkout the update guide to see all the changes needed to make for
your version ( or above ) of installation.

https://aniketmalik.github.io/woostore_pro_documentation/update-guide

**Comment by gaurav-netscapelabs** [comment]
It shows to update to version v2.1.0 but i have v2.1.1
![image](https://user-images.githubusercontent.com/75060994/132844017-e6434b22-7c44-4c9b-9005-9613ce978fba.png)
![image](https://user-images.githubusercontent.com/75060994/132844210-b8d92dfa-2e21-4094-9bac-df05ac9abc69.png)

**Comment by AniketMalik** [comment]
Yes, it's a version ahead of it so it is built on top of 2.1.0 so you need
to perform the steps as well.

**Comment by gaurav-netscapelabs** [comment]
from where i can get downloaded to downgrade my version. also i have deactivate CoCart Lite

**Comment by AniketMalik** [comment]
You do not need to downgrade the version. Just perform the steps from the
update guide for the closest lower version of the plugin if you have not.

**Comment by gaurav-netscapelabs** [comment]
I followed all the steps upgraded my WP, having WooStore Pro Api v2.1.1 also i have deactivated CoCart Plugin
but the output is still same.
Please help
![image](https://user-images.githubusercontent.com/75060994/132846439-2e7baf1e-0af3-42b3-806d-68fc18aeeaf6.png)

**Comment by AniketMalik** [comment]
Please let me know does this occur in all the products or just this one
specific product ?

This product is simple, variable or which other type ?

Please let me know this information to better debug the issue.

**Comment by gaurav-netscapelabs** [comment]
I have also created a new test product you can check as below.
https://dev.wholesalebarbersupply.com/product/test/

But still, I am facing the same issue 
![image](https://user-images.githubusercontent.com/75060994/133059330-d3ad9ac7-982f-4aff-8979-3f599714ee11.png)

**Comment by AniketMalik** [comment]
Please downgrade the woocommerce version to v4.9.3 as version 5 has some breaking changes and try again.

**Comment by gaurav-netscapelabs** [comment]
Do you have any URL of the Plugin from where I can find v4.9.3 WooCommerce to download?

**Comment by AniketMalik** [comment]
https://developer.woocommerce.com/releases/

**Comment by gaurav-netscapelabs** [comment]
![image](https://user-images.githubusercontent.com/75060994/133062382-3b2905f1-e0fc-4542-a294-198a7c8f2b75.png)
after downgrading i found this and my whole application crashed

**Comment by AniketMalik** [comment]
Sir, you should always create a backup of your system before installing any plugin as they can break some functionality.

Please check if you could use version 5.2

**Comment by gaurav-netscapelabs** [comment]
Thanks for reminding me for backup but I have done that.

I have successfully downgraded to recommended 5.2.3
but still output is the same 

![image](https://user-images.githubusercontent.com/75060994/133065642-75ee868e-bd2b-478d-b0f9-54c27cb0337f.png)

**Comment by AniketMalik** [comment]
The best compatible version is 4.9.3 Please check if you can use that. 

However a new implementation of the cart will be pushed in about 2 weeks. If you are not able to use the version 4.9.3 then please wait for the new implementation to be pushed which will be compatible with woocommerce's latest releases.

Thank you.

**Comment by gaurav-netscapelabs** [comment]
Yes that happend with all product
Unable to downgrade version to 4.9.3 I shared earlier also 
https://github.com/AniketMalik/ecommerce-store-support/issues/12#issuecomment-918020547
Please do that asap as I am waiting but I am worried that you haven't worked on latest version as it's already almost 2 months 
How can I get once you update.

**Comment by AniketMalik** [comment]
Will let you know about the update on this thread.

Thank you for your patience.

**Comment by AniketMalik** [comment]
Please send me the following at aniketmalikwork@gmail.com so that I can test your functionality on my end.

Wordpress Url
Consumer Key
Consumer Secret

**Comment by gaurav-netscapelabs** [comment]
Please check your inbox.

**Comment by AniketMalik** [comment]
I could not find it. Please share your email address as well so that I can
search for it.

**Comment by AniketMalik** [comment]
Received

**Comment by gaurav-netscapelabs** [comment]
Thanks, waiting for your feedback.

**Comment by gaurav-netscapelabs** [comment]
Are you able to achieve a result, waiting for your update?

**Comment by AniketMalik** [comment]
Currently debugging the same.

Do you still have CoCart Lite plugin installed on your website ?

**Comment by gaurav-netscapelabs** [comment]
Yes, i have installed but not activated it yet is there anything I have do with it...
![image](https://user-images.githubusercontent.com/75060994/133214546-4cccb652-62ee-486b-94d4-1430110b1d1a.png)

**Comment by AniketMalik** [comment]
Please delete the plugin as it is not required when you have WooStore Pro Api plugin 2.x.x

**Comment by gaurav-netscapelabs** [comment]
Okay deleted.  are you able to achieve the expected result now?

**Comment by AniketMalik** [comment]
Hello. I have created a mock website with the latest version of WooCommerce plugin ( 5.6 ) and used the latest woostore pro api plugin with it to test if the problem is from woocommerce or my plugin.

In the testing I was able to add as well as remove the product from the cart without any issues. The REST API for cocart to edit the cart information about the logged in/out user worked as expected. So there is not any problem with the compatibility of both the above mentioned plugins. 

This error is most likely caused by some other plugin which modifies the following function:
`WC_Product->is_purchasable()` with the hook filter `woocommerce_is_purchasable` as this piece of code returns **false ** which causes that error.

I recommend you to make a dev version of the site. 
Disable all other plugins except those required by the WooStore Pro application.
Then test the cart functionality.

Please note that some plugins can still affect the output to the product response when disabled.

**Comment by gaurav-netscapelabs** [comment]
![image](https://user-images.githubusercontent.com/75060994/133233910-39fcdc07-9974-49c6-aef5-1a4eaa716791.png)
I have disabled all plugins only two are activated but the output is still the same 403

**Comment by gaurav-netscapelabs** [comment]
Can you share your latest version of WooStore Pro api

**Comment by AniketMalik** [comment]
It's the same as you have installed it.

Please log out of the application, close it and then login again. This will clear out all the out of sync settings.

This could also be caused by a theme or caching plugin. Please clear all the cache from your website as well.
Please also check if you have any security plugin which is causing the REST API Requests to not modify the cart.

Please note that Disabling plugins might not help in some poorly created plugins as they already set their functions to the hooks and filters which might still run.

**Comment by gaurav-netscapelabs** [comment]
Okay...
Is there any place where i can check what are the hooks are been used also which of things I have to remove which may cause issues in my application?

**Comment by AniketMalik** [comment]
Unfortunately I cannot guide you through that as it is relate to wordpress hooks and filter with plugins which is out side my support area.

However you can start looking at the logs for woocommerce. But it won't be enough as not all plugins log the events they fire.

Please check out the wordpress documentation.

**Comment by gaurav-netscapelabs** [comment]
But the issue is i have installed your plugin and still it's not compatible so the issue is related to that, I am disappointed with this one that there is no solution on this.

**Comment by AniketMalik** [comment]
Unfortunately the way wordpress works is that you can install any amount of plugins and all of them have the power to manipulate data sent from the website to other applications. This cannot be guaranteed as to which plugin might cause an issue with other plugin. 

However, I am creating a native checkout process which will bypass this functionality. Also For your use case specifically, i will create a separate cart implementation which will save the data in it's own database table. But this might take sometime as I am already working on new features for the application.

**Comment by gaurav-netscapelabs** [comment]
okay, I am waiting for that solution and it's very important to please let me know asap as you're able to resolve this issue.

**Comment by AniketMalik** [comment]
Will let you know when the feature is developed.

**Comment by gaurav-netscapelabs** [comment]
is there way i can disable my last license key and enable new key 
I was trying to add in new testing version of WP and also removed key but the issue is still same from one hour
![image](https://user-images.githubusercontent.com/75060994/133381188-a4857802-008e-42f9-9a1e-ac3f0aaab2d5.png)

**Comment by AniketMalik** [comment]
Add the plugin on your previous website. Then deactivate it from there.

Then you'll be able to activate it on your new website.

**Comment by gaurav-netscapelabs** [comment]
I have deactivated and deleted plugin from 3 website I have used and I am trying to use on old one but it keep saying the same...
what should I have to do that

**Comment by AniketMalik** [comment]
Please e-mail me your purchase code at ***@***.*** and I'll
reset it.

Thank you.

**Comment by gaurav-netscapelabs** [comment]
aniketmalikwork@gmail.com you mean this email

**Comment by AniketMalik** [comment]
Yes. Send me the following to aniketmalikwork@gmail.com

1. Purchase code
2. Website Url ( old and new both if it is different )
3. Admin email address ( old and new both if the it is different )

**Comment by gaurav-netscapelabs** [comment]
Sent Please check.

**Comment by AniketMalik** [comment]
Reset Complete.
