### ISSUE TITLE
Help in Installing Flutter Please

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#13]
Hi Aniket, I just purchased Woostore Pro from Codecanyon.net and am having problems in installing the flutter sdk, therefore, i cant start working on my application, kindly help me as soon as possible, its urgent!

Kind Regards
- ishan

**Comment by AniketMalik** [comment]
Please share your issue here.

**Comment by Ishan2610** [comment]
Can you kindly check the issue for yourself through anydesk

It would be greatly appreciated as its urgent!

**Comment by AniketMalik** [comment]
Unfortunately remote support is not available at this point.

Please explain your issue here. You can also add screenshots.

**Comment by AniketMalik** [comment]
Unfortunately, remote support is not available at this point.

Please explain your issue here. You can also include screenshots as well.

**Comment by Ishan2610** [comment]
![issue](https://user-images.githubusercontent.com/88072634/127358534-831d8c70-27b1-4121-a688-efd9efbe488d.JPG)
This issue is coming

**Comment by AniketMalik** [comment]
You need to install Android Studio. It is also mentioned in the documentation. Please read the full documentation before trying to run the application.

You can skip the part where you need to install Chrome web browser as it is only required for web development for flutter or debugging purposes.

**Comment by Ishan2610** [comment]
HI i have already installed android studio
and configured it properly
Why is it still saying that i havent installed it

**Comment by AniketMalik** [comment]
The installation process might have been corrupted for some reason. I recommend you to install android studio afresh from the website. Please use the latest version. If the setup prompts you to edit the environment variables, then do allow it.

**Comment by Ishan2610** [comment]
Hi
I just installed android studio today
From the documentation link only, It would be easier if you could just check for yourself through anydesk, as its very urgent

Kind regards

**Comment by AniketMalik** [comment]
I would have started a remote desktop support if I could but it is not possible on my end at this point.

Please run the setup for android studio again. That shall fulfil any remaining settings. Also during the setup, Android studio ask to install SDKs for android emulator, those must also be installed if you wish to run the application android emulator.

**Comment by Ishan2610** [comment]
hi, anydesk is free and will download in less than 30 seconds.
Please just try it as it would really mean a lot and help me out a ton!!

**Comment by AniketMalik** [comment]
Please send me your id and password for the same. 
I will be able to connect for at most 10 minutes. If the issue is not resolved. I will assign you a slot tomorrow.

**Comment by Ishan2610** [comment]
Ok thankx a lot

**Comment by Ishan2610** [comment]
Have you downloaded Anydesk?

**Comment by AniketMalik** [comment]
Please send me your information

**Comment by Ishan2610** [comment]
722 453 458

**Comment by AniketMalik** [comment]
Its invalid. Kindly send the correct info. I have limited time

**Comment by Ishan2610** [comment]
Hi, kindly paste the id in the circled section and then i will accept your id

![referrence](https://user-images.githubusercontent.com/88072634/127363281-860ce3f5-afbc-471c-9978-c822b8fa799a.JPG)

**Comment by Ishan2610** [comment]
hi i have accepted

**Comment by AniketMalik** [comment]
![image-3](https://user-images.githubusercontent.com/33630047/127367908-7d6e0e71-eeeb-4872-b31f-a3cd8ba8d827.png)

1. In dropdown list open “plugins”
2. Search for “flutter” and install this plugin together with dart.
3. Restart the Android Studio and open a new terminal.
4. You should be able to create a flutter project in Android Studio and “flutter doctor” should work now.

Please try this solution before changing you name in PC

**Comment by AniketMalik** [comment]
Solution 2:

Run the following command to change the directory directly in flutter config.

```shell
flutter config --android-studio-dir "C:\Program Files\Android\Android Studio"
```
