### ISSUE TITLE
I have started on it

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#14]
HI aniket, i have done everything you told me to do but again the flutter doctor is showing many errors, If you are free
Kindly see the error through anydesk

722 453 458

Kind regards

**Comment by AniketMalik** [comment]
Please try to run the application. If it shows any error while running then share the error message here. 

Thank you.

**Comment by Ishan2610** [comment]
HI it would be easier if you could just come online on anydesk for just 5 to 10 minutes like last time

Kind regards
