### ISSUE TITLE
Product Short description & product image zooming

### ISSUE THREAD

**Issue by kskwe** [AniketMalik/ecommerce-store-support#15]
Dear AniketMalik,

Wonderful Application Nice work.

I have some clarification 

1. Product Short description not available in product page.

2. Two Colum product page image zooming ( https://ibb.co/JK5zSLn ) - How to zoom out  

3. How to change splash screen background color "White"

Thanks in advance

**Comment by AniketMalik** [comment]
Hello.

Thank you for your interest in the application.

Here are the answers:


1. Yes, this has not been added instead the application shows the main description directly. Please let me know where you want it to be included and I'll help you with the same.

2. The item card image covers the image fully. However if you want you can change the functionality by adding the following:

**File:**
lib/shared/itemCard.dart

**Line Number:**
Below 334

**Addition:**
Add the following line
```dart
fit: BoxFit.contain,
```

After the change line 332 - 336 should look like:

```dart
    return ExtendedCachedImage(
      imageUrl: displayImage,
      borderRadius: ThemeGuide.borderRadius,
      fit: BoxFit.contain,
    );
```

3. To do this you need to make the following changes:

**File:**
lib/screens/splash/splash.dart

**Line Number:**
On 78,79,80

**Update:**

Change the following from this
```dart
gradient: ThemeGuide.isDarkMode(context)
              ? AppGradients.mainGradientDarkMode
              : AppGradients.mainGradient,
```

to this

```dart
  color: Colors.white,
```

Please let me know if you have any further questions

**Comment by kskwe** [comment]
Dear AniketMalik,

Thank you for your fast reply.

1. My suggestion Short description (https://ibb.co/KWnpRdF) above description. "Short Description" same like description tab. what is your opinion?

2 & 3 fixed thank you.

**Comment by AniketMalik** [comment]
1. This functionality can be included in the application for your specific case, however most clients does not use short descriptions for their products and I have not received any requests prior to this to add short descriptions in the product screen.

**Comment by kskwe** [comment]
Dear AniketMalik,

I think most of the people needed short description. Possible to add next update.

Thank you.

**Comment by AniketMalik** [comment]
Yes, I will add this in the requested features list. Please let me know if you need this now. I can send you a patch to add this functionality.

Thank you.

**Comment by kskwe** [comment]
Dear AniketMalik,

Yes, Please share

Thank you.

**Comment by AniketMalik** [comment]
Please let me know if the short description should be always open or not

**Comment by kskwe** [comment]
Dear AniketMalik,

always open 

Thank you

**Comment by AniketMalik** [comment]
Please share your email address to receive the updated files

**Comment by kskwe** [comment]
kamalnath.slm@gmail.com
