### ISSUE TITLE
Product Review Issues 

### ISSUE THREAD

**Issue by kskwe** [AniketMalik/ecommerce-store-support#17]
Dear AniketMalik,

In our app Customer without purchase the product can put review & rating. One customer can review multiple times in the same product. I have enable in woocommerce Show "verified owner" label on customer reviews. ( https://ibb.co/fQtLRHk )

Please fix this issues

**Comment by AniketMalik** [comment]
Please share the version of the application you are using.

**Comment by kskwe** [comment]
Version – v1.12.0

**Comment by AniketMalik** [comment]
In this version any user who is not logged in cannot add a review as the application forces the user to be logged in to add a review. 

However in a new update, only the users who have actually bought the product will be able to add a review. This feature is being developed and shall be released soon,

**Comment by kskwe** [comment]
okay Please update this feature as soon as possible.

Thank you.

**Comment by AniketMalik** [comment]
Please download the latest version v1.13.0 from codecanyon which has the updated review system.

It has other changes as well, to know more about them please checkout the change logs: https://github.com/AniketMalik/ecommerce-store-support/blob/main/change_logs.md

**Comment by kskwe** [comment]
Dear AniketMalik,

salute for you fast support and update

Keep rocking

Thank you

**Comment by AniketMalik** [comment]
Please download the version v1.13.1 as it fixes an issue where the add a review button was not shown on the variable product.

Have a great time.

Regards,
Aniket Malik

**Comment by kskwe** [comment]
Okay Thank you

Have a great day
