### ISSUE TITLE
Native payment checkout & Deeplink Notification

### ISSUE THREAD

**Issue by kskwe** [AniketMalik/ecommerce-store-support#18]
Dear AniketMalik,

I saw in comment section that you said this feature in pipeline

1.Native payment gateway checkout (Razorpay)

2. Deeplink push Notification

Both feature when will come.

Thanks in Advance.

**Comment by AniketMalik** [comment]
Deep link push notifications has already been added in v1.12.0

Native payment gateway feature has been put on hold as a new version of the application with an online APP BUILDER is being developed which will allow the users to change the application's screens from the backend on the fly.

Will notify you when the feature will be implemented.

**Comment by kskwe** [comment]
How to send deeplink push notification? (CUSTOMER CLICK THE NOTIFICATION, IT SHOULD OPEN IN APP’S PRODUCT OR CATEGORY PAGE)

I have checked firebase cloud message but no deeplink options.

**Comment by AniketMalik** [comment]
A deep link is not required to be attached to a push notification. The purpose of deep link is to allow the users to see the liked content from anywhere in the application whether or not they have installed the application on their device.

On the other hand, a push notification is used to send specific information to the user.

In my opinion what you are trying to achieve is that you want to send push notification to the users related to specific product of category and when they click on it, the native application screen appears.

Is that it ?

**Comment by kskwe** [comment]
Yes, 

One signal docs & screen shot for your reference
https://ibb.co/kmzNkRR
https://documentation.onesignal.com/docs/links

**Comment by kskwe** [comment]
okay, How to send push notification with deeplink using firebase cloud message?

**Comment by kskwe** [comment]
Dear AniketMalik,

For example if Customer click the notification (assume the user already had the app ) dose the click take him directly to the product page or category page inside the app.

I think flutter SDK available in one signal Pls refer - https://documentation.onesignal.com/docs/flutter-sdk-setup

Thank You

**Comment by kskwe** [comment]
Dear AniketMalik,

Waiting for your reply.

**Comment by AniketMalik** [comment]
I have checked the sdk for one signal and they have not implemented the deeplink feature in flutter sdk.

A push notification can only be sent to a user who has installed the application on their device.

The function you are looking for is not implemented by default and will have to be implemented on custom demand and hence will be charged separately.

Thank you
