### ISSUE TITLE
Facing issues in flutter doctor

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#19]
Hi Aniket, We have already talked
I have made all the necessary changes told by you but still many errors are coming in flutter doctor
If possible, Kindly look into the issue yourself through andesk, it would be greatly appreciated!

Kind regards

**Comment by Ishan2610** [comment]
HI
Still awaiting a reply?

**Comment by AniketMalik** [comment]
Have you tried reinstalling all the components to setup your development environment ? If yes , please list them down.

Also share the error from the terminal in the comments.

**Comment by Ishan2610** [comment]
HI, as its urgent, it would be greatly appreciated if you could look into it yourself as it would be very quick 
I have also reinstalled all the components but still it isnt working

KIndly reply fast as its urgent

**Comment by AniketMalik** [comment]
Please share the error from the flutter doctor terminal window.

You problem is not related to the application but is related to the setup of development machine which is not covered in the support. This issue is related to the development machine that you are working on and have not been encountered ever before. However I will help you to rectify this issue as soon as possible. Please allow time to search for the best possible solution.

**Comment by AniketMalik** [comment]
Please try this command from the terminal or cmd:

```shell
flutter config –android-studio-dir=”YOUR ANDROID STUDIO DIRECTORY PATH”
```

Please replace the YOUR ANDROID STUDIO DIRECTORY PATH with the actual path for android studio directory.

**Comment by Ishan2610** [comment]
C:\Users\Ishan Kapoor\Downloads\codecanyon-ZqT5Bs7n-woostore-pro-woocommerce-full-flutter-ecommerce-app\WooStore Pro - Full Package - v1.12.0\mobile-application\woostore_pro>
  
->

'flutter' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AniketMalik** [comment]
You have not added flutter to your path variables which was part of the installation process.

Please follow the steps from the official guide to add flutter to your path and then follow the above mentioned solution.
Link: https://flutter.dev/docs/get-started/install/windows#update-your-path

**Comment by Ishan2610** [comment]
![Capture](https://user-images.githubusercontent.com/88072634/129442181-7dd5938b-5a79-492c-8548-a89ca74cf013.JPG)
These errors are coming, i have installed android studio and flutter again and completed the setup wizard of android studio and also updated the flutter path variable,

Kindly help me through anydesk as it would mean the world to me, I have been trying to fix the issue since 2 days but havent been able to and also its really urgent that i start working on the app...🙏🙏


Kind regards
Ishan

**Comment by Ishan2610** [comment]
Hi
Still Awaiting a reply, Kindly reply as soon as possible as its very urgent

Kind regards

**Comment by Ishan2610** [comment]
Hi 
![Capture](https://user-images.githubusercontent.com/88072634/129445511-b7372428-2f2a-4791-85c6-34bdb6bec08c.JPG)

I have fixed all of the issues except for the "Chrome_Executable" one, Kindly specify the steps or the command to fix this issue?

Kind regards

**Comment by AniketMalik** [comment]
Chrome browser is required only for the web development and the application is used on mobile devices.  You can leave is as it is. It's not an issue.
