### ISSUE TITLE
[Feature request] OTP login

### ISSUE THREAD

**Issue by kskwe** [AniketMalik/ecommerce-store-support#20]
Dear AniketMalik,

[Feature request] Please add OTP login feature. Very useful & important feature.

Possible to add soon.

Thanks in advance.

**Comment by kskwe** [comment]
Dear AniketMalik,

Google firebase (Free) OTP login plugin for your reference

https://wordpress.org/plugins/mobile-login-woocommerce/

**Comment by kskwe** [comment]
Dear AniketMalik,

Request Possible to add ASAP

Thanks in advance

**Comment by AniketMalik** [comment]
Will add the OTP feature in the next update.  👍

**Comment by AniketMalik** [comment]
Feature added in version 2.2.0

**Comment by kskwe** [comment]
Hello,

I have seen Gif. Page navigates to you are not a robot page. can you please fix it?

Also, App OTP login user how to login in the website?

Thanks in advance.

**Comment by AniketMalik** [comment]
The otp login flow in through Firebase Phone Login. The "recaptcha" page is
used by Firebase SDK and is not through the application implementation.

The otp login is made for the application and not the website.

**Comment by kskwe** [comment]
okay But App Otp login user how to login into the website?

Like amazon & Flipkart...

**Comment by AniketMalik** [comment]
Currently the setup does not add a phone otp login in website.
