### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#23]
Hi, i am still getting the following error when i try to run the application on the emulator

"Gradle task assembleDebug failed with exit code 1"

Kindly help me, i would appreciate it if you could look into the issue yourself through Anydesk, thanks in advance

Kind regards

**Comment by AniketMalik** [comment]
Not enough data.
Please share the full contents of the error.

**Comment by Ishan2610** [comment]
![h](https://user-images.githubusercontent.com/88072634/129454999-55ea8df2-480f-4bd6-9d1b-adace8f308b7.JPG)
Hi, the build error has been fixed but now this is coming in the app on the emulator

Kindly help

**Comment by AniketMalik** [comment]
This is not enough data.
For all your further issues while running the application kindly share the error stated in the debug console of the android studio.

**Comment by Ishan2610** [comment]
Hi Kindly consider checking the issue through anydesk, as it would help a TON!
and also its very urgent thus it would be quicker

Thanks & Regards

**Comment by AniketMalik** [comment]
I am not available for remote desktop support currently. Kindly share the problem here. The issue from the screen shot seems that you have not completely followed the setup steps from the documentation.

**Comment by Ishan2610** [comment]
Hi kindly tell me whenever you will be free to help me through the installation, wether today or tomorrow, and i will be ready at that time but its a request from my side for you to make this installation process quicker and help me through the steps as its extremely urgent

Kind regards

**Comment by AniketMalik** [comment]
Sir I charge $200 for setup on local machine through remote desktop support. I helped you previously for free. Kindly share the issues you have here. My schedule is very tightly packed.

**Comment by Ishan2610** [comment]
Hi, i am very sorry for the inconvenience caused

But there is no error, the build window is perfectly fine, its just that when i open the app, "Something went wrong" error is coming.

**Comment by AniketMalik** [comment]
Then please check the documentation as you might have misses some setup steps.

Have you added your wordpress url and the keys for woocommerce to work ?
Is REST API enabled on your website ?

**Comment by Ishan2610** [comment]
Hi

I am completing the firebase authentication but when i try to open the IOS project in Xcode, there is no option saying "Open in xcode" upon right click, kindly help

Kind regards

**Comment by AniketMalik** [comment]
You need a mac to use Xcode.

**Comment by Ishan2610** [comment]
Hi, so what can i do now, since i dont have a mc? 😅😅
