### ISSUE TITLE
Product Layout Height

### ISSUE THREAD

**Issue by kskwe** [AniketMalik/ecommerce-store-support#24]
Dear AniketMalik,

How to Reduce Product layout height https://ibb.co/MGcMmJJ (Change to square layout)

Thanks in Advance

**Comment by AniketMalik** [comment]
You can modify the same from the following file:
*lib/themes/themeGuide.dart *on line number *17. *Modify the ratio till you
reach the desired result.

```dart

static const double productItemCardAspectRatio = 1 / 2;

```

**Comment by kskwe** [comment]
Dear AniketMalik,

i have changed "static const double productItemCardAspectRatio = 1 / 1;

But not fit the product content - (Name, Price & Review)

**Comment by AniketMalik** [comment]
If you were not able to achieve the desired results then please try again with following variables in the same file as previous.

```dart
static const double productItemCardAspectRatio = 1 / 2;
static const double horizontalProductListContainerAspectRatio = 1 / 1;
```

In case you are not able to reach your desired result, then send me your design that you are trying to reach and I'll send you the desired changes.

**Comment by kskwe** [comment]
Dear AniketMalik,

I need this kind layout size
![Untitled11](https://user-images.githubusercontent.com/88721143/130264007-7e773768-336e-472f-8ac4-d469eb81f398.png)

**Comment by AniketMalik** [comment]
Please try the following changes:

File: **lib/shared/itemCard.dart**
Line: 105

```dart
```

**Comment by AniketMalik** [comment]
Please try the following changes:

File: lib/shared/itemCard.dart
Line: 105

Change the flex value to 2
```dart
flex: 2,
```

File: **lib/themes/themeGuide.dart**
LIne: 17

Change the value as below:
```dart
static const double productItemCardAspectRatio = 1 / 1.6;
```

**Comment by kskwe** [comment]
You are the genius. 

Thanks a lot.

**Comment by AniketMalik** [comment]
Thank you for your appreciation. I highly appreciate it.

**Comment by kskwe** [comment]
Dear AniketMalik,

i have changed the value grid view nice but list view too big. Pls guide how to fix.

![WhatsApp Image 2021-09-23 at 8 54 46 PM](https://user-images.githubusercontent.com/88721143/134537245-34231706-108b-4588-bda2-69f4f4997371.jpeg)

**Comment by AniketMalik** [comment]
Please make modifications to the variables below:

File: `lib/themes/themeGuide.dart`

```dart
static const double productItemCardAspectRatio = 1 / 2;
static const double horizontalProductListContainerAspectRatio = 1 / 1;
```
