### ISSUE TITLE
Apple Login WooStorePro_API No Endpoint for AppleLogin

### ISSUE THREAD

**Issue by angelolaris** [AniketMalik/ecommerce-store-support#27]
Hello Aniket,

I have a problem with Apple Login which is stopping my app from being published in the Apple App Store

After Debugging

Looking at the Woocommerce.dart package there seems to be a problem with the Apple Login.

The Apple login is invalid compare to Facebook and Google

The           "$baseUrl/wp-json/woostore_pro_api/flutter_user/apple_login?email=$email&display_name=$fullName&user_name=${email.split("@")[0]}");

Is not url encoded. Also the login api is not exposed

When executed

On my test environment

{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}

https://bbtd.microangeloit.com.au/wp-json/woostore_pro_api/flutter_user/apple_login?xxxxxxxxxxxxx

Can you explain what is meant to happen and how you got Apple Login to work as per version
[ v1.5.2 ] - 30th April 2021 - Aniket Malik
Improved - Apple Sign in capabilities and workflow.

Here is the Woocommerce.dart for your reference

/// Login with apple
  Future<WooCustomer> loginApple({String email, String fullName}) async {
    try {
      var endPoint = Uri.parse(
          "$baseUrl/wp-json/woostore_pro_api/flutter_user/apple_login?email=$email&display_name=$fullName&user_name=${email.split("@")[0]}");

      var response = await http.get(endPoint);

      var decoded = jsonDecode(response.body);

      if (decoded['user'] == null || decoded["cookie"] == null) {
        throw Exception(decoded['message']);
      }

      // Update the cookie
      userCookie = decoded['cookie'];
      await _localDbService.updateUserCookie(decoded['cookie']);

      // Set the auth token
      if (decoded['jwt_token'] is String) {
        _authToken = decoded['jwt_token'];
        await _localDbService.updateSecurityToken(decoded['jwt_token']);
      }

      return WooCustomer.fromJson(decoded['user']);
    } catch (_) {
      rethrow;
    }
  }

Thanks in advance

**Comment by AniketMalik** [comment]
There was a typo in the url of the apple login. This has been fixed in the latest versions. 

Please download the latest package from codecanyon.

**Comment by angelolaris** [comment]
Hello Aniket

Thanks for your quick response

I am now getting {"code":"invalid_email","message":"Can't get the email to create account.","data":{"status":400}}

For 
https://bbtd.microangeloit.com.au/wp-json/woostore_pro_api/flutter_user/apple_login?email=angelo.laris@gmail.com&display_name=null&user_name=angelo.laris

Looking at the code

The isset is not working.

Can you confirm what could be the problem 

public function apple_login($request)
  {
    $email = $request['email'];
    $display_name = $request['display_name'];
    $user_name = $request['user_name'];
    if (!isset($email)) {
      return parent::sendError("invalid_email", "Can't get the email to create account.", 400);
    }
    return $this->createSocialAccount($email, $display_name, $display_name, "", $user_name);
  }

**Comment by AniketMalik** [comment]
The response states that the user who is trying to create an account has not provided a valid email address which is required by wordpress and woocommerce to create a user account. Please add the email address to your apple login method to complete the process.
