### ISSUE TITLE
Please solve cloud firebase error 

### ISSUE THREAD

**Issue by jadhav48** [AniketMalik/ecommerce-store-support#28]
Please any Solutions

What went wrong: Could not determine the dependencies of task ’:app:transformClassesAndResourcesWithR8ForDebug’. > Could not resolve all dependencies for configuration ’:app:debugRuntimeClasspath’. > Could not load module metadata from C:\Users\HP\.gradle\caches\modules-2\metadata-2.71\descriptors\androidx.lifecycle\lifecycle-common\2.2.0\fc7e8eef251519086b6ee9788cba4dd2\descriptor.bin
Try: Run with—stacktrace option to get the stack trace. Run with—info or—debug option to get more log output. Run with—scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 1m 6s The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility. Building plugin cloud_firestore… Running Gradle task ‘assembleAarRelease’... Exception: The plugin cloud_firestore could not be built due to the issue above.

**Comment by AniketMalik** [comment]
Please run the following command and share the output.

```shell
flutter doctor
```

The error states that there is some inconsistency in your caches for the gradle. Please run the following command from the directory **woostore_pro** to fetch the packages:

```shell
flutter pub get
```

**Comment by jadhav48** [comment]
i try this step
but new error show

[Fatal Error] exoplayer-common-2.14.1.pom:2:1: Content is not allowed in prolog.
> Could not resolve com.google.android.exoplayer:exoplayer-common:2.14.1.
         > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-common/2.14.1/exoplayer-common-2.14.1.pom
            > Content is not allowed in prolog.
![image](https://user-images.githubusercontent.com/89478886/130717153-dba1621c-21d3-4bd2-b6d2-9a1d70ce0b64.png)

**Comment by AniketMalik** [comment]
The application building process requires internet access to download the dependencies. 

Please connect to an internet source.

This error is not related to the application but is due to your development machine.

**Comment by jadhav48** [comment]
internet connection on 
but not solver again
![image](https://user-images.githubusercontent.com/89478886/130805768-ad45ac78-9d70-42a3-ad3e-3074727c02ef.png)

**Comment by AniketMalik** [comment]
Try this

1. Close android studio.
2. Delete all the contents of below directories.

`C:\Users\USER_NAME\.android\build-cache`
`C:\Users\USER_NAME\.android\cache`
`C:\Users\USER_NAME\.gradle\caches`
```
3. Restart Android Studio

**Comment by AniketMalik** [comment]
Please use HTTPS scheme.
Please complete the setup and then run the application. 

If you see some error in the debug console, please add them in your following issues.

Have a great time.

Regards,
Aniket Malik
