### ISSUE TITLE
 Don't show profile settings or other account information when user is not logged in 

### ISSUE THREAD

**Issue by saud-kh** [AniketMalik/ecommerce-store-support#3]
When a user is not logged and tries to access the orders they get a bool error (see image below)

in my opinion the whole section should be disabled unless the user is logged in as they can't see orders or modify profile or account settings

![Simulator Screen Shot - iPhone 11 - 2021-04-04 at 03 41 30](https://user-images.githubusercontent.com/45364874/113495122-c9e51a80-94f7-11eb-91f1-7a0876a49e52.png)

**Comment by AniketMalik** [comment]
Thanks for reporting this issue.

An early update with the fix is coming up. Please expect the update to come in within 2 days.

**Comment by AniketMalik** [comment]
The error has been resolved an an update has been pushed, you can download the application in a few days with the fix.
