### ISSUE TITLE
Cannot add products to the cart in the application but adds in the web 

### ISSUE THREAD

**Issue by Enowiz** [AniketMalik/ecommerce-store-support#34]
Throws this error in terminal when I try to add a product in Cart

DEBUG | Headers' set-cookie for coCart is null, returning

**Comment by AniketMalik** [comment]
This is not an error but a warning which is not critical. Please show all the logs and specifically if you see any logs with the word ERROR in them.

**Comment by Enowiz** [comment]
![Capture](https://user-images.githubusercontent.com/37063134/131355296-b4472186-f3ba-498b-96c1-c54448f916cd.PNG)

**Comment by AniketMalik** [comment]
Please let me know when does this error occurs ?

**Comment by Enowiz** [comment]
Whenever i add a product to cart or tap on buy now

**Comment by AniketMalik** [comment]
Please share the following:
1. Version of WooStore Pro mobile application.
2. Version of WooStore Pro Api wordpress plugin.

**Comment by Enowiz** [comment]
1. WooStore Pro - Full Package - v1.13.1
2. WooStore Pro Api wordpress plugin Version 2.1.1

**Comment by AniketMalik** [comment]
Please share the following on this email address: aniketmalikwork@gmail.com

Website url
Consumer secret
Consumer key

**Do not share them here.**

I will test the application on my end with your setting and trouble shoot the issue.

**Comment by AniketMalik** [comment]
Sir you are using the wrong URL for your website. Please change the url you are using from
`https://beerbrosug.com` to `https://www.beerbrosug.com` and the application will work perfectly.

Please see the video attached.

https://user-images.githubusercontent.com/33630047/131359783-ae4a4e13-ade8-4bd0-92d5-f72bd7fb33ad.mov

**Comment by AniketMalik** [comment]
Please give me a good review on codecanyon if you like the application and support. It will encourage me to bring new and exciting features to the application frequently. Thank you.
