### ISSUE TITLE
Firebase configuration for IOS

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#35]
Hi

The firebase configuration for android has been successfully done but for the IOS configuration, according to the documentation, i have to add the GoogleService-Info.plist file into android studio assets using xcode but since i work on windows pc, it is not possible for me to open xcode, hence is there any other way to add the info.plist file to android studio except using xcode?
(I have attached screenshots for your referrence)
![nn](https://user-images.githubusercontent.com/88072634/131717880-3707a4d0-b908-4d0a-8320-f01d764a13c3.JPG)
![ll](https://user-images.githubusercontent.com/88072634/131717888-c1b6604a-4679-408b-8c35-4be37d972d2f.JPG)

**Comment by AniketMalik** [comment]
GoogleService-Info.plist has to be added to the Runner folder in the ios directory.

However you need a mac to build the application for iOS. Without a mac you will not be able to build an application for iOS as it requires a team id added to the xcode. Alternatively you can see the following url to build an application for iOS without a mac: 
https://flutter.dev/docs/deployment/ios#create-a-build-archive-with-codemagic-cli-tools

**Comment by Ishan2610** [comment]
Hi

For the time being, may i porceed with just building the application for android and later on continue with the IOS application. I hope it wont interfere with the android application building process?

Kind regards
Ishan

**Comment by AniketMalik** [comment]
Yes you can proceed with only android application without any problem. You can build application for which ever platform you may like.

Have a great time.

Regards,
Aniket Malik
