### ISSUE TITLE
Issue in creating new keystore

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#36]
Hi

I have downloaded git bash tool and right clicked the woostore_pro directory to open the git bash terminal.
The first time i copied the command given in the documentation "bash tools/create-keystore.sh", it asked me to delete the previous keystore, which i did but afterwards when i pasted the command again and executed it, it is showing an error "Command not found".
Kindly help

Thanks and regards
Ishan
![a](https://user-images.githubusercontent.com/88072634/131846022-11be3c83-e9a4-4f44-ae8f-e42488045843.JPG)

**Comment by AniketMalik** [comment]
You need to add the keytool to your path so that the keytool is recognized from any window. Once you perform the steps mentioned below, you will need to close the bash window and open again for the effects to take place.

Please follow the steps from the link below:
https://codewithandrea.com/articles/keytool-command-not-found-how-to-fix-windows-macos/#add-the-keytool-folder-to-your-system-path-on-windows

**Comment by Ishan2610** [comment]
Hi

I have successfully created the keystore file  but later on in the process, when i have to copy this command (bash tools/create-debug-fingerprint.sh) in the terminal window to get the SHA-1 key, the following error is coming?
(Error shown in image)
![Capture](https://user-images.githubusercontent.com/88072634/131851392-e4678e90-385e-4e09-8c0b-5b41030806e6.JPG)

**Comment by AniketMalik** [comment]
For windows users all the commands have to be run from the git bash. Please read the documentation carefully. It is mentioned for the windows platform

**Comment by Ishan2610** [comment]
Hi, i know this is a small question but can you please tell me which hash key do i have to copy from the terminal window as none of them look like the example you have provided in the documentation.
![jj](https://user-images.githubusercontent.com/88072634/131854254-ac558a7d-807d-4d79-bfc7-cfd2c7e2302e.JPG)

Thanks in advance
Ishan

**Comment by AniketMalik** [comment]
The keys will be unique for every machine as if they were to be same for
all the applications, app stores won't be able to differentiate between
them.

Yes you need to provide your website's privacy policy and terms and
conditions along with the home page.

**Comment by Ishan2610** [comment]
So out of the two in the image, which key do i need to save for later purpose?

**Comment by AniketMalik** [comment]
Sir, as mentioned in the documentation as well, you need BOTH these keys
for Facebook login which is next in the setup. One of them is for debug app
and one for release app.

Kindly read the complete documentation as all these answers to your
questions have already been mentioned there.

In case you see an error, please contact via the same method.

Thank you.

**Comment by Ishan2610** [comment]
Hi, i have already verified my domain "https://remkart.com" in google search console

![sd](https://user-images.githubusercontent.com/88072634/131864048-5980a6cf-4515-43a3-bb57-4d6d488c385f.JPG)

This error is coming

Kind regards
Ishan

**Comment by AniketMalik** [comment]
Add the domain remkart.com and check for your registered domain from the link for google console.
