### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#37]
Hi

I recently got notified that there has been a new update for "Woo store pro" source code and would like to update my recent version of the project but i am just confused on how to execute the update and also, if i update the version, will my previous work be deleted because i have already made my app and its functioning properly. 
Kindly guide me on how i can update my project without losing all my previous made changes as this is my first time working with a pre-coded project from codecanyon.

Kind regards
Ishan

**Comment by Ishan2610** [comment]
Hi

Also i as my app is fully built, i am trying to build the APK file through Build>Flutter>Build APK. But an error code is showing.
It's showing that the "Gradle task assembleRelease failed with exit code 1". Kindly help me fix this issue.

![kkhi](https://user-images.githubusercontent.com/88072634/132099134-117c525e-5c81-4b40-a33d-e388fee34d00.JPG)

**Comment by AniketMalik** [comment]
You should use GIT Version control system. However there are very small changes to the application so please send me your email id and I'll send you the updates in that email and the steps to apply them. This way you won't have to redo your changes to the application.

**Comment by AniketMalik** [comment]
Have you completed all the necessary changes required from the documentation ?
Also please use the following link to build the application for android:
https://flutter.dev/docs/deployment/android#building-the-app-for-release

**Comment by Ishan2610** [comment]
My mail is: ishan.kapoor2006@gmail.com

and also i tried to build the application by the way mentioned in the link as well, through putting in the command "flutter build apk --split-per-abi" in the terminal window but still it is showing the exact same error "Code 1",

Kindly help me fix it

**Comment by AniketMalik** [comment]
This could be a result of various things. Some of them are listed below:

• check if you have any **assets** which are not founded by `pubspec.yaml` or maybe for typo. You will get a warning for typo after you run `flutter pub get`
• Some error in the dart source files. If you have edited the application yourself and modified the code, you might have broken some functionality in the application's source files. You can see these in the dart analyser in the Tools Window -> Dart Analysis in android studio.
• Or your Flutter SDK path is not correctly added to the android studio.

Please make sure that all the above are without any errors.

What all changes have you made in the application ?

**Comment by Ishan2610** [comment]
Hi

I have checked "Flutter pub get" and there is no error

I think there is an issue in the build file because the "GradleException" is marked red. 
![jjk](https://user-images.githubusercontent.com/88072634/132100813-2325fa08-0601-4daa-947c-feaa1d8a9ff9.JPG)

I tried to go to local.properties but there, flutter sdk has been added correctly

Kind regards

**Comment by AniketMalik** [comment]
GradleException is a non issue, it's an ide thing. It can be ignored.

Please let me know the changes you made in the application.

**Comment by Ishan2610** [comment]
i havent made any changes in the application except the ones told in the documentation. i didnt even open anything else except for the steps told in the documentation

**Comment by AniketMalik** [comment]
Pl share the contents of terminal after running "flutter doctor"

Please try to run the application in debug mode and tell me if there is any
problem.

**Comment by Ishan2610** [comment]
![Uploading jh.JPG…]()

**Comment by AniketMalik** [comment]
Please run the following command:

```shell
flutter doctor --android-licenses
```

This shall activate the licenses.

Please follow the steps below:
1. Run `flutter clean` from the terminal from within the `woostore_pro` directory
2. Try to run the application in debug mode now. If there are any errors then share the logs or screen shot of the same.

I'll help you rectify the issues with your development machine.

**Comment by Ishan2610** [comment]
![snipp](https://user-images.githubusercontent.com/88072634/132104430-150d22ee-24ed-4479-bf68-cf51b38f000c.JPG)

I have ran flutter clean.
And also can you kindly tell me how to run the application in debug mode?

**Comment by AniketMalik** [comment]
Your dev machine's android setup is not complete.

Please follow the steps from the following link:
https://flutter.dev/docs/get-started/install/windows#agree-to-android-licenses

**Comment by Ishan2610** [comment]
Hi

I told you that whenever i try to agree to the android licenses - 

Error: Could not find or load main class Kapoor\AppData\Local\Android\Sdk\cmdline-tools\Latest\bin\\..
Caused by: java.lang.ClassNotFoundException: Kapoor\AppData\Local\Android\Sdk\cmdline-tools\Latest\bin\\//

This error shows

**Comment by AniketMalik** [comment]
Kindly download the GIT Bash and use it's terminal to complete the commands.

Download link:
https://git-scm.com/downloads

**Comment by Ishan2610** [comment]
The same error is showing even when i run it in git bash

**Comment by AniketMalik** [comment]
It is because of the space in the name of the path.

Let me find a solution or else you'll have to change the name.

Have you added java home to your path variables ?

**Comment by Ishan2610** [comment]
Yes i have added java jdk version 16.0.2 / Bin in the path variables as mentioned in the documentation

**Comment by AniketMalik** [comment]
You need to have a version of JAVA 8 as well on your machine. As mentioned in this link:
https://flutter.dev/docs/get-started/install/windows#agree-to-android-licenses

**Comment by Ishan2610** [comment]
I have installed Java version 8 right now, do i need to update any path in the path variables?

**Comment by AniketMalik** [comment]
Set the JAVA_HOME to the version 8's JDK folder

**Comment by Ishan2610** [comment]
![sn](https://user-images.githubusercontent.com/88072634/132105683-41739c72-f733-4693-bbd2-310b007cda68.JPG)

**Comment by AniketMalik** [comment]
Please let me know which version of android studio are you using ?

**Comment by Ishan2610** [comment]
Android Studio Arctic Fox | 2020.3.1 Patch 2

**Comment by Ishan2610** [comment]
Hi, is there any update on how to solve this problem?

Kind regards

**Comment by AniketMalik** [comment]
Can you try to run the application in debug mode on an android emulator ?

You can use the comman "flutter run" from the terminal or using the "Bug"
icon from the top navigation menu tool bar.

**Comment by Ishan2610** [comment]
Hi i have ran the application on my phone in debug mode using the command "Flutter run" and its working perfectly fine. but still i am not able to build the application??

**Comment by Ishan2610** [comment]
Hi is there any update?

**Comment by AniketMalik** [comment]
You should use GIT Version control system. However there are very small
changes to the application so please send me your email id and I'll send
you the updates in that email and the steps to apply them. This way you
won't have to redo your changes to the application.

**Comment by Ishan2610** [comment]
Hi i was talking about the build application error

**Comment by AniketMalik** [comment]
I suggest you to use the POWER SHELL application in windows to execute the command as the path to the file used to create the apk in your development machine has spaces in it which is the root cause of this problem. 

In windows the path must be enclosed in double quotes so that the OS can intercept it correctly.

**Comment by AniketMalik** [comment]
Please share your AnyDesk id, i'll remote check the same

**Comment by Ishan2610** [comment]
sure - 722 453 458

**Comment by AniketMalik** [comment]
You can try the following:

Create a new keystore file as now you have added the JAVA version 8 to your path.
After that try to run the following command:

```shell
flutter build apk --split-per-abi --no-tree-shake-icons
```

This might remove the latest error we got for the permissions for upload.keystore file which could have been created while the JAVA version was 16 on your machine

**Comment by Ishan2610** [comment]
do i need to create new SHA-1 fingerprints as well?

**Comment by Ishan2610** [comment]
![th](https://user-images.githubusercontent.com/88072634/132203439-3b40e35f-eaa6-4c3a-83ff-aaafbe6e51f0.JPG)

Thanks a lot!

Kind regards

**Comment by AniketMalik** [comment]
Happy to help you. 

Please give me a good review if you like the application and the support. It will encourage me to build more features for the application.
