### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by angelolaris** [AniketMalik/ecommerce-store-support#39]
Hello Aniket

I am trying to send a push notification with a message to no eval.

I get the push notification but no data

curl -X POST -H "Authorization:key=BLAH" -H "Content-Type: application/json" -d '

{

   ["to":"/topics/PROMOTIONS",]([url]([url]([url](url))))

   "title":"This is a test",

   "body":"This is the body",

   "data":

   {

      "title":"Your title",    

      "message":"Your message"

   }

}' https://fcm.googleapis.com/fcm/send

Thanks

**Comment by AniketMalik** [comment]
You are using the wrong notification object. Please see the FCM
notification object for more information.
