### ISSUE TITLE
[Bug] Unable to checkout

### ISSUE THREAD

**Issue by saud-kh** [AniketMalik/ecommerce-store-support#4]
The app does not allow you to checkout (this error also happens on the demo app)
![Simulator Screen Shot - iPhone 11 - 2021-04-04 at 03 46 31](https://user-images.githubusercontent.com/45364874/113495201-7cb57880-94f8-11eb-9fb1-fa42b2e41fcb.png)

**Comment by AniketMalik** [comment]
I am able to perform the checkout without any problems on the demo application.

However this occurs when you've not set up the JWT Secret token in the wp_config.php file or you've not set the token secret in Simple JWT plugin or Tye secret token does not match.

Please check that you've used the same JWT token secret key in both the places. Please refer to setup document for more information.

**Comment by AniketMalik** [comment]
Are you facing this issue when the user is not logged in ?

**Comment by AniketMalik** [comment]
Do you see this issue when the user is logged in or not logged in ( guest Customer ) ?

**Comment by AniketMalik** [comment]
The error has been resolved and an update has been pushed. It shall be live within a few days. You can download it from codecanyon itself.

Please use the application over an HTTPS connection to avoid unwanted behaviour.
