### ISSUE TITLE
Splash screen color change

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#40]
Hi

Firstly, i am still facing a problem in activating the social login for "Woostore-pro". I have tried following all the steps in the documentation but still an error shows when the user tries to login through google/facebook. 
Secondly, as its not given in the documentation, can you please guide me on how to just change the background color of the splash screen with the logo, as my logo is colorful, it looks better with a white background rather than a colorful one and as the background for the splash screen is just connected with the primary color,  cant seem to change it so kindly help me

Thanks in advance
kind regards

**Comment by AniketMalik** [comment]
Sir, The social logins has a very specific setup and even a single in-consistency will result in it not working.
In the online documentation you need to follow the below in exact order:

1. [Create Release Keys](https://aniketmalik.github.io/woostore_pro_documentation/mobile-app-setup/release-keys)
2. [Social Login](https://aniketmalik.github.io/woostore_pro_documentation/mobile-app-setup/social-login)

Now the above mentioned must be in exact same order as the release and debug SHA-1 Fingerprint and Key hashes are dependent on the upload.keystore that should be create for android and iOS has their own different setup.

Also the debug keys and fingerprints will be different for each machine that you are using to develop.

=================================================================================

### Splash Screen

To change the background gradient to color please make the following modifications:

File: `lib/screens/splash/splash.dart`
Line number: `77 - 81`

From:

```dart
decoration: BoxDecoration(
  gradient: ThemeGuide.isDarkMode(context)
      ? AppGradients.mainGradientDarkMode
      : AppGradients.mainGradient,
),
```

To:

```dart
decoration: BoxDecoration(
  color: ThemeGuide.isDarkMode(context)
    ? AppColors.backgroundDark
    : AppColors.backgroundLight,
),
```

Here the `AppColors.backgroundDark` and `AppColors.backgroundLight` can be replaced with your prefered.

To change the logo please add your image in the `lib/assets/images` directory and the edit the splash.dart file on line number 90 with the path to your image.

**Comment by Ishan2610** [comment]
Hi, thanks a lot for the help but right now I dont have time to enable social login so is there a way to disable social login in the source code and just keep a standard login/register page?
And also i want to remove these columns from the filter page (Image attached), i went through the documentation, kindly tell me how i can remove these search filters?

Kind regards
![m](https://user-images.githubusercontent.com/88072634/133773756-3ec5cc37-ab74-4e6a-b24e-21a7315779c3.JPG)

**Comment by AniketMalik** [comment]
You can remove the widget named `FilterAttributes()` from the following files to remove it from all places:

lib/screens/search/widgets/filterModal/searchFilterModal.dart
lib/screens/allProducts/widgets/filterModal/allProductsFilterModal.dart
lib/screens/tags/widgets/filter_modal/tag_products_filter_modal.dart

**Comment by Ishan2610** [comment]
And how can i disable social login for the app?

**Comment by AniketMalik** [comment]
Please edit the file: `lib/screens/login/login.dart` and remove the lines from 58 to 61 as follows:

```dart
DividerWithText(text: lang.or),
const SizedBox(height: 20),
const SocialLoginRow(),
const SizedBox(height: 30),
```

**Comment by Ishan2610** [comment]
Hi i have removed FilterAttributes() from every single required place, but its still showing all the filter attributes?

**Comment by AniketMalik** [comment]
Please restart the application

**Comment by Ishan2610** [comment]
Hi is there a way to make login compulsory, in other ways, remove "Continue without login"?

**Comment by Ishan2610** [comment]
Hi, The social login icons have been removed from the main login page from account/account/login but when the user is not logged in, in every other page like "My downloads","My points","My orders". The social login icons are there, kindly help

**Comment by AniketMalik** [comment]
You can remove the "Continue without login" button by modifying the following:

File: lib/screens/onBoarding/onBoarding.dart
Remove the line from 160 - 164

```dart
_BuildButton(
                  title: lang.continueWithoutLogin,
                  color: LightTheme.mPurple,
                  onPress: _goToTabbar,
                ),
```

====================================

Remove social icons from other login screens:

File: lib/screens/login/widgets/loginFromX.dart
Remove the lines from 66 to 69

```dart
DividerWithText(text: lang.or),
              const SizedBox(height: 20),
              const _SocialLogin(),
              const SizedBox(height: 30),
```

**Comment by Ishan2610** [comment]
Hi

DividerWithText(text: lang.or),
const SizedBox(height: 20),
const _SocialLogin(),
const SizedBox(height: 30),

`DividerWithText(text: lang.or),
const SizedBox(height: 20),
const _SocialLogin(),
const SizedBox(height: 30),
`

**Comment by Ishan2610** [comment]
Hi, the app is successfully built and i am able to build an APK file of the app but as per google play store guidelines, a creator is not able to upload an APK and is only allowed to upload an app bundle but when i try to build an app bundle through Build>Flutter>Build app bundle, (Image attached), error code 1 is showing. Kindly help me
![app](https://user-images.githubusercontent.com/88072634/133873766-e57f7ae3-5b0d-466d-adfd-1a90120928f7.JPG)

**Comment by AniketMalik** [comment]
Insufficient error message.

Please paste the contents of the whole error message.

Please build the app bundle using this link: https://flutter.dev/docs/deployment/android#build-an-app-bundle

**Comment by Ishan2610** [comment]
> flutter build appbundle --no-shrink

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Failed to open output file 'C:\Users\Ishan Kapoor\Downloads\codecanyon-CUb5fEly-woostore-pro-woocommerce-full-flutter-ecommerce-app\WooStore Pro - Full Package - v1.13.1\mobile-application\woostore_pro\build\app\intermediates\flutte
r\release\flutter_assets\packages/eva_icons_flutter/lib/fonts/evaicons.ttf'. The parent directory may not exist, or the user does not have permission to create this file.

Failed to open output file 'C:\Users\Ishan Kapoor\Downloads\codecanyon-CUb5fEly-woostore-pro-woocommerce-full-flutter-ecommerce-app\WooStore Pro - Full Package - v1.13.1\mobile-application\woostore_pro\build\app\intermediates\flutte
r\release\flutter_assets\packages/cupertino_icons/assets/CupertinoIcons.ttf'. The parent directory may not exist, or the user does not have permission to create this file.

Failed to open output file 'C:\Users\Ishan Kapoor\Downloads\codecanyon-CUb5fEly-woostore-pro-woocommerce-full-flutter-ecommerce-app\WooStore Pro - Full Package - v1.13.1\mobile-application\woostore_pro\build\app\intermediates\flutte
r\release\flutter_assets\fonts/MaterialIcons-Regular.otf'. The parent directory may not exist, or the user does not have permission to create this file.



FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        45.3s
Gradle task bundleRelease failed with exit code 1

I am getting this error message when i try to build the appbundle without R8

**Comment by AniketMalik** [comment]
Please add this flag `--no-tree-shake-icons` to you `flutter build` command.

For example

```shell
flutter build appbundle --no-tree-shake-icons
```

**Comment by Ishan2610** [comment]
And also, i have visited the link already but there also, its only mentioned to use the command `Flutter build appbundle` to make an appbundle

**Comment by AniketMalik** [comment]
> Please add this flag `--no-tree-shake-icons` to you `flutter build` command.
> 
> For example
> 
> ```shell
> flutter build appbundle --no-tree-shake-icons
> ```

Please use this and try.

**Comment by Ishan2610** [comment]
Hi, it worked.

Can you please tell me the significance of this flag `--no-tree-shake-icons` as it worked last time as well when i was trying to make an APK file. Does it remove anything specific from the app build file?

Kind regards
Thank you!
