### ISSUE TITLE
Flutter App bundle

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#41]
Hi Aniket,

Hi, the app is successfully built and i am able to build an APK file of the app but as per google play store guidelines, a creator is not able to upload an APK and is only allowed to upload an app bundle. 
But when i am trying to build an app bundle through Build>Flutter>Build app bundle, (Image attached), error code 1 is resulting

![app](https://user-images.githubusercontent.com/88072634/133878044-a3143e75-9e43-4bdb-985c-4a9cc05f7d09.JPG)

Thanks in advance
Kind regards

**Comment by AniketMalik** [comment]
Insufficient error message.

Please paste the contents of the whole error message.

Please build the app bundle using this link: https://flutter.dev/docs/deployment/android#build-an-app-bundle

**Comment by AniketMalik** [comment]
Please add this flag `--no-tree-shake-icons` to you `flutter build` command.

For example

```shell
flutter build appbundle --no-tree-shake-icons
```
