### ISSUE TITLE
Home Page design changes

### ISSUE THREAD

**Issue by kskwe** [AniketMalik/ecommerce-store-support#42]
Hello AniketMalik,

I want to small changes in Home page. 

1.How to add cart & notification in headed, Bottom Favorite icon. (Green mark)

2.How to reduce space (Red mark)

![homep](https://user-images.githubusercontent.com/88721143/133889893-b9e3d231-c5f6-43ed-bba9-fdad1acad08b.jpeg)

Thanks in advance.

**Comment by AniketMalik** [comment]
To add action buttons to home page app bar please make desired changes to `lib/screens/home/home.dart` on widget `SliverAppBar`.

To reduce the red area highlighted, please edit the file: `lib/screens/home/widgets/sections_view.dart` on line number 61

```dart
padding: const EdgeInsets.only(top: 15),
```

Decrease the number 15 to your desired value.

**Comment by kskwe** [comment]
Hello AniketMalik,

Can you explain more about how to make changes SliverAppBar. (Cart & notification icon in header and Bottom Favorite icon)

(To add action buttons to home page app bar please make desired changes to lib/screens/home/home.dart on widget SliverAppBar.)

Regards

**Comment by kskwe** [comment]
Hello AniketMalik,

Kindly look into this.

Thanks in advance

**Comment by AniketMalik** [comment]
Apologies for the late reply.
I have edited the files for your liking.
Please share your email address to get the updated files.

**Comment by kskwe** [comment]
kamalnath.slm@gmail.com

No issues. Thank you for your support.

**Comment by AniketMalik** [comment]
The email has been sent with the updated files for your needs.

Please give me a good review on codecanyon if you like the application and support. It will encourage me to bring new and exciting features to the application frequently. Thank you.

**Comment by kskwe** [comment]
Dear AniketMalik,

Sure.

Thank you for your wonderful support.

**Comment by AniketMalik** [comment]
Please give me a good review on codecanyon if you like the application and support. It will encourage me to bring new and exciting features to the application frequently. Thank you.

**Comment by kskwe** [comment]
Already done

![Capture1111](https://user-images.githubusercontent.com/88721143/134361270-f290c78c-dfe0-48de-8c5a-c4b9890bb84b.PNG)

**Comment by AniketMalik** [comment]
I know you have given me a great review. Thank you. 
I was hoping if you could give me another if possible.

Have a great time.

Regards,
Aniket Malik

**Comment by kskwe** [comment]
Sure AniketMalik

**Comment by AniketMalik** [comment]
Thank you @kskwe
