### ISSUE TITLE
Sign up ERROR

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#43]
Hi Aniket, kindly reply as soon as possible

(Image attached)
I have built the app and followed each and every step carefully, but while trying to create a new account in the app, this error is showing.
I have tried my best to solve it but i cant find the solution. Kindly help me ASAP

Kind regards
Ishan

![Screenshot_20210918_222155](https://user-images.githubusercontent.com/88072634/133896459-723ceafd-e5a8-4ffa-b3cf-63dd63dfbd29.jpg)

**Comment by Ishan2610** [comment]
Hi kindly reply ASAP.....

Kindest regards

**Comment by AniketMalik** [comment]
Please share the error logs from android studio for me to debug the issue.

From the images it can be seen that the response from your server was erroneous which is why the application could not anticipate it. Hence the error.

**Comment by Ishan2610** [comment]
Hi, there is no error in the application, I am not running the app in debug mode and have installed the app's apk file in my phone. While building the app, there was no error

**Comment by AniketMalik** [comment]
Please run the application in debug mode on your dev machine, then try to create an account and if an error comes send me the logs..

**Comment by Ishan2610** [comment]
`ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (27189):   ERROR │ type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
I/flutter (27189):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (27189):   ERROR │ #0   WooCommerce.createCustomerWithApi (package:woocommerce/woocommerce.dart:493:9)
I/flutter (27189):   ERROR │ #1   <asynchronous suspension>
I/flutter (27189):   ERROR │ #2   WooService.signUp (package:woostore_pro/services/woocommerce/woocommerce.service.dart:73:34)
I/flutter (27189):   ERROR │ #3   <asynchronous suspension>
I/flutter (27189):   ERROR │ #4   AuthController.signUp (package:woostore_pro/controllers/authController.dart:243:20)
I/flutter (27189):   ERROR │ #5   <asynchronous suspension>
I/flutter (27189):   ERROR │ #6   _SignUpFormState.buttonFun (package:woostore_pro/screens/signup/form/signupForm.dart:59:24)
I/flutter (27189):   ERROR │ #7   <asynchronous suspension>
I/flutter (27189):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (27189):   ERROR │ ⛔ Error sign up
I/flutter (27189):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
`




This error message is showing in the debug terminal window, kindly help me to resolve it

**Comment by AniketMalik** [comment]
Which version of WooStore Pro Api wordpress plugin are you using ? Is it
activated ?

**Comment by Ishan2610** [comment]
i am using version "Woostore pro - 2.1.0" and yes i have activated it..

Kind regards

**Comment by AniketMalik** [comment]
Please share the website url so that I can debug it on my end.

The signup system works perfectly on my end.

**Comment by Ishan2610** [comment]
The website url: https://remkart.com

If you need the username and password, kindly share your gmail address

**Comment by AniketMalik** [comment]
As I suspected before, there is no problem in the application or the plugin.

You have not added a SECRET JWT KEY to the woostore pro api.

```json
{
    "cookie": "HIDDEN USER VALUE",
    "user_id": "HIDDEN USER VALUE",
    "jwt_token": {
        "errors": {
            "jwt_auth_bad_config": [
                "JWT is not configurated properly, please contact the admin"
            ]
        },
        "error_data": {
            "jwt_auth_bad_config": {
                "status": 403
            }
        }
    }
}
```

**Comment by Ishan2610** [comment]
Hi, yes the issue is fixed now but still in place of the user name and email address, "Not available" is visible..

![kkk](https://user-images.githubusercontent.com/88072634/133898514-768ae310-8457-4148-a5a0-25999a6ae9de.JPG)

**Comment by AniketMalik** [comment]
The application is out of sync. Please restart it.

**Comment by Ishan2610** [comment]
HI, If possible, can you please tell me where i can change the Complied SDK version from 29 to 30 according to google play guidelines as i cant find the option in the build.gradle file?

Kind regards

**Comment by AniketMalik** [comment]
woostore_pro/android/app/build.gradle line 30

**Comment by Ishan2610** [comment]
Hi,

Version code 29 has already been used. Try another version code. 

This error is showing while uploading my app bundle, can you kindly help me in solving this as i have tried but couldnt find any way online

Kind regards

**Comment by AniketMalik** [comment]
In file pubspec.yaml on line number 15, please increase the number 29 with
1 to make it 30 or any any number other than that.

**Comment by Ishan2610** [comment]
Hi, in the recent update, "Sync gradle files" was removed, so how can i sync the gradle files for the changes to take affect?
