### ISSUE TITLE
ANDROID COMPILING ISSUE

### ISSUE THREAD

**Issue by jatinderarora90** [AniketMalik/ecommerce-store-support#44]
![Screenshot 2021-09-21 at 5 21 15 PM](https://user-images.githubusercontent.com/9926123/134178120-1207ee4f-35aa-4006-9d79-9bbdcf2ee8d4.png)

Getting attached screenshot error!!!

**The named parameter 'builder' isn't defined.**

lib/routes/router.gr.dart:58:9: Error: No named parameter with the name 'builder'.
        builder: (_) {
        ^^^^^^^
../../../../Downloads/flutter2/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.0/lib/src/router/auto_route_page.dart:123:3: Context: Found this candidate, but the arguments don't match.
  CupertinoPageX({
  ^^^^^^^^^^^^^^

**Comment by AniketMalik** [comment]
Required information:

Flutter version ( run "flutter doctor" and attach result )
WooStore pro application version from pubspec.yam file

Did you make any changes or modifications to the application source code however small they may be ? ( list them all ).

Possible solutions:
Rerun dart analysis server or restart android studio to analyse the project again.

**Comment by jatinderarora90** [comment]
![Screenshot 2021-09-22 at 11 11 58 AM](https://user-images.githubusercontent.com/9926123/134289268-f6419aba-723e-4061-885e-3b6bd4ded5d3.png)

Launching lib/main.dart on GM1901 in debug mode...
Running Gradle task 'assembleDebug'...
../../../../Downloads/flutter2/.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../Downloads/flutter2/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../Downloads/flutter2/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

**Comment by AniketMalik** [comment]
Your pub cache is out of date.
Please run

```shell
flutter pub cache repair
```

then run
```shell
flutter clean
```

and then try to run the application. Please note that you need to run the commands from within the woostore pro directory.

**Comment by jatinderarora90** [comment]
../../../../Downloads/flutter2/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:100:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../../Downloads/flutter2/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);


AFTER FOLLOWING ABOVE STEPS

**Comment by AniketMalik** [comment]
As you can see the error is caused by the plugin `wakelock_platform_interface-0.2.0` which isn't a part of the application WooStore Pro. It must be used by a different application. This plugin is not up to date and hence needs to be deleted from your file system.

Please delete the above mentioned package from the path `Downloads/flutter2/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0`.

Do this with all the outdated packages and plugins until a clean build is possible.

**Comment by jatinderarora90** [comment]
Error: No named parameter with the name 'builder'.
        builder: (_) {
        ^^^^^^^
../../../../Downloads/flutter2/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.0/lib/src/router/auto_route_page.dart:123:3: Context: Found this candidate, but the arguments don't match.
  CupertinoPageX({
  ^^^^^^^^^^^^^^
lib/routes/router.gr.dart:63:9: Error: No named parameter with the name 'builder'.
        builder: (_) {
        ^^^^^^^

**Comment by AniketMalik** [comment]
Sir, have you edited any if the source files?
Which version of the application are you using?

**Comment by jatinderarora90** [comment]
i did not edited any source file...

**Comment by AniketMalik** [comment]
Please share the Version of the application ?

**Comment by jatinderarora90** [comment]
i did not got the about application version??

**Comment by AniketMalik** [comment]
Please go to pubspec.yaml file. See the version from there and let me know

**Comment by jatinderarora90** [comment]
name: woostore_pro
description: WooStore Pro is a new Flutter application for Ecommerce and fully compatible with WooCommerce.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.13.1+29

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  eva_icons_flutter: ^3.0.0
  another_flushbar: ^1.10.24
  flutter_facebook_login: ^3.0.0
  flutter_form_builder:
    git: https://github.com/Sportner/flutter_form_builder.git
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  get_it: ^6.0.0
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  introduction_screen: ^2.1.0
  photo_view: ^0.12.0
  logger: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  smooth_page_indicator: ^0.2.3
  url_launcher: ^6.0.2
  flutter_swiper: ^1.1.6
  event_bus: ^2.0.0
  # WooCommerce
  woocommerce:
    path: ../packages/woocommerce
  dio: ^4.0.0
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
  expandable: ^5.0.1
  webview_flutter: ^2.0.9
  webview_cookie_manager: ^2.0.5
  package_info: ^2.0.2
  badges: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  dropdown_search: ^0.6.3
  # Firebase
  firebase_messaging: ^10.0.3
  cloud_firestore: ^2.3.0
  firebase_auth: ^2.0.0
  firebase_dynamic_links: ^2.0.7
  # Local Notifications
  flutter_local_notifications: ^6.0.0
  flutter_html: ^2.1.0
  # Localization
  flutter_localizations:
    sdk: flutter
  # Database
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # Share
  share_plus: ^2.1.4
  # Change Package Name
  change_app_package_name: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  auto_route_generator: ^2.1.0
  build_runner: null

  flutter_launcher_icons: ^0.9.0


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/svg/
    - lib/assets/svg/flags/
    - lib/assets/json/
    - lib/assets/gifs/
flutter_intl:
  enabled: true


  fonts:
    - family: Jost
      fonts:
        - asset: lib/assets/fonts/Jost-Regular.ttf
    - family: Jost
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf

**Comment by jatinderarora90** [comment]
please check above

**Comment by AniketMalik** [comment]
You are using an outdated version of the application.
Please download the latest package from codecanyon. The latest version is **1.14.1**

**Comment by sohamd99** [comment]
I'm having same issue.

**The named parameter 'builder' isn't defined.**

dart analysis.

**Comment by AniketMalik** [comment]
> I'm having same issue.
> 
> **The named parameter 'builder' isn't defined.**
> 
> dart analysis.

Please download the latest package from codecanyon. The latest version is 1.14.1

**Comment by sohamd99** [comment]
Downloaded few mins ago. 1.14.1

**Comment by sohamd99** [comment]
Same error!

**Comment by AniketMalik** [comment]
Please share your router.gr.dart file from lib/routes/router.gr.dart file.

**Comment by sohamd99** [comment]
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouteGenerator
// **************************************************************************

import 'package:auto_route/auto_route.dart' as _i1;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/material.dart';

import '../navigation/tabbar.dart' as _i5;
import '../screens/accountSettings/accountSettings.dart' as _i20;
import '../screens/addAddress/addAddress.dart' as _i22;
import '../screens/address/address.dart' as _i21;
import '../screens/allProducts/allProducts.dart' as _i26;
import '../screens/cards/addNewCard.dart' as _i23;
import '../screens/cards/cards.dart' as _i17;
import '../screens/cart/cart.dart' as _i14;
import '../screens/categories/categorisedProducts.dart' as _i24;
import '../screens/changePassword/changePassword.dart' as _i19;
import '../screens/contact/contact.dart' as _i18;
import '../screens/downloads/downloads.dart' as _i30;
import '../screens/editProfile/editProfile.dart' as _i16;
import '../screens/favorites/favorites.dart' as _i13;
import '../screens/home/home.dart' as _i12;
import '../screens/home/viewModel/homeSection.viewModel.dart' as _i35;
import '../screens/login/enums/loginFromXEnum.dart' as _i36;
import '../screens/login/login.dart' as _i8;
import '../screens/login/widgets/loginFromX.dart' as _i29;
import '../screens/myOrders/myOrders.dart' as _i10;
import '../screens/myOrders/order.model.dart' as _i33;
import '../screens/myOrders/trackOrder/trackOrder.dart' as _i11;
import '../screens/notifications/notifications.dart' as _i31;
import '../screens/onBoarding/onBoarding.dart' as _i9;
import '../screens/points/points.dart' as _i28;
import '../screens/product/product.dart' as _i6;
import '../screens/profile/profile.dart' as _i15;
import '../screens/search/search.dart' as _i25;
import '../screens/search/viewModel/searchViewModel.dart' as _i34;
import '../screens/settings/settings.dart' as _i27;
import '../screens/signup/signup.dart' as _i7;
import '../screens/splash/splash.dart' as _i4;
import '../screens/tags/tag_products.dart' as _i32;
import 'guards.dart' as _i3;

class AppRouter extends _i1.RootStackRouter {
  AppRouter(
      {_i2.GlobalKey<_i2.NavigatorState> navigatorKey,
      @required this.authGuard})
      : super(navigatorKey);

  final _i3.AuthGuard authGuard;

  @override
  final Map<String, _i1.PageFactory> pagesMap = {
    SplashScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i4.SplashScreen();
        }),
    TabbarNavigationRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i5.TabbarNavigation();
        }),
    ProductScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<ProductScreenRouteArgs>(
              orElse: () => const ProductScreenRouteArgs());
          return _i6.ProductScreen(key: args.key, id: args.id);
        }),
    SignupRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i7.Signup();
        }),
    LoginRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i8.Login();
        }),
    OnBoardingRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i9.OnBoarding();
        }),
    MyOrdersRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i10.MyOrders();
        }),
    TrackOrderRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<TrackOrderRouteArgs>(
              orElse: () => const TrackOrderRouteArgs());
          return _i11.TrackOrder(key: args.key, order: args.order);
        }),
    HomeRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i12.Home();
        }),
    FavoritesRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i13.Favorites();
        }),
    CartRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i14.Cart();
        }),
    ProfileRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i15.Profile();
        }),
    EditProfileRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i16.EditProfile();
        }),
    CardsScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i17.CardsScreen();
        }),
    ContactScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i18.ContactScreen();
        }),
    ChangePasswordRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i19.ChangePassword();
        }),
    AccountSettingsRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i20.AccountSettings();
        }),
    AddressScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<AddressScreenRouteArgs>(
              orElse: () => const AddressScreenRouteArgs());
          return _i21.AddressScreen(key: args.key, isShipping: args.isShipping);
        }),
    AddAddressRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i22.AddAddress();
        }),
    AddNewCardScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i23.AddNewCardScreen();
        }),
    CategorisedProductsRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<CategorisedProductsRouteArgs>(
              orElse: () => const CategorisedProductsRouteArgs());
          return _i24.CategorisedProducts(
              key: args.key,
              category: args.category,
              searchCategory: args.searchCategory,
              childrenCategoryList: args.childrenCategoryList);
        }),
    SearchScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i25.SearchScreen();
        }),
    AllProductsRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<AllProductsRouteArgs>(
              orElse: () => const AllProductsRouteArgs());
          return _i26.AllProducts(
              key: args.key, homeSectionDataHolder: args.homeSectionDataHolder);
        }),
    SettingsRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i27.Settings();
        }),
    PointsScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i28.PointsScreen();
        }),
    LoginFromXRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<LoginFromXRouteArgs>(
              orElse: () => const LoginFromXRouteArgs());
          return _i29.LoginFromX(key: args.key, loginFrom: args.loginFrom);
        }),
    DownloadsScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i30.DownloadsScreen();
        }),
    NotificationScreenRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (_) {
          return const _i31.NotificationScreen();
        }),
    TagProductsRoute.name: (routeData) => _i1.CupertinoPageX<dynamic>(
        routeData: routeData,
        builder: (data) {
          final args = data.argsAs<TagProductsRouteArgs>(
              orElse: () => const TagProductsRouteArgs());
          return _i32.TagProducts(key: args.key, tag: args.tag);
        })
  };

  @override
  List<_i1.RouteConfig> get routes => [
        _i1.RouteConfig(SplashScreenRoute.name, path: '/'),
        _i1.RouteConfig(TabbarNavigationRoute.name, path: '/tabbar-navigation'),
        _i1.RouteConfig(ProductScreenRoute.name, path: '/product-screen'),
        _i1.RouteConfig(SignupRoute.name, path: '/Signup'),
        _i1.RouteConfig(LoginRoute.name, path: '/Login'),
        _i1.RouteConfig(OnBoardingRoute.name, path: '/on-boarding'),
        _i1.RouteConfig(MyOrdersRoute.name,
            path: '/my-orders', guards: [authGuard]),
        _i1.RouteConfig(TrackOrderRoute.name, path: '/track-order'),
        _i1.RouteConfig(HomeRoute.name, path: '/Home'),
        _i1.RouteConfig(FavoritesRoute.name, path: '/Favorites'),
        _i1.RouteConfig(CartRoute.name, path: '/Cart'),
        _i1.RouteConfig(ProfileRoute.name, path: '/Profile'),
        _i1.RouteConfig(EditProfileRoute.name,
            path: '/edit-profile', guards: [authGuard]),
        _i1.RouteConfig(CardsScreenRoute.name, path: '/cards-screen'),
        _i1.RouteConfig(ContactScreenRoute.name, path: '/contact-screen'),
        _i1.RouteConfig(ChangePasswordRoute.name,
            path: '/change-password', guards: [authGuard]),
        _i1.RouteConfig(AccountSettingsRoute.name, path: '/account-settings'),
        _i1.RouteConfig(AddressScreenRoute.name,
            path: '/address-screen', guards: [authGuard]),
        _i1.RouteConfig(AddAddressRoute.name,
            path: '/add-address', guards: [authGuard]),
        _i1.RouteConfig(AddNewCardScreenRoute.name,
            path: '/add-new-card-screen'),
        _i1.RouteConfig(CategorisedProductsRoute.name,
            path: '/categorised-products'),
        _i1.RouteConfig(SearchScreenRoute.name, path: '/search-screen'),
        _i1.RouteConfig(AllProductsRoute.name, path: '/all-products'),
        _i1.RouteConfig(SettingsRoute.name, path: '/Settings'),
        _i1.RouteConfig(PointsScreenRoute.name,
            path: '/points-screen', guards: [authGuard]),
        _i1.RouteConfig(LoginFromXRoute.name, path: '/login-from-x'),
        _i1.RouteConfig(DownloadsScreenRoute.name,
            path: '/downloads-screen', guards: [authGuard]),
        _i1.RouteConfig(NotificationScreenRoute.name,
            path: '/notification-screen'),
        _i1.RouteConfig(TagProductsRoute.name, path: '/tag-products')
      ];
}

class SplashScreenRoute extends _i1.PageRouteInfo {
  const SplashScreenRoute() : super(name, path: '/');

  static const String name = 'SplashScreenRoute';
}

class TabbarNavigationRoute extends _i1.PageRouteInfo {
  const TabbarNavigationRoute() : super(name, path: '/tabbar-navigation');

  static const String name = 'TabbarNavigationRoute';
}

class ProductScreenRoute extends _i1.PageRouteInfo<ProductScreenRouteArgs> {
  ProductScreenRoute({_i2.Key key, String id})
      : super(name,
            path: '/product-screen',
            args: ProductScreenRouteArgs(key: key, id: id));

  static const String name = 'ProductScreenRoute';
}

class ProductScreenRouteArgs {
  const ProductScreenRouteArgs({this.key, this.id});

  final _i2.Key key;

  final String id;
}

class SignupRoute extends _i1.PageRouteInfo {
  const SignupRoute() : super(name, path: '/Signup');

  static const String name = 'SignupRoute';
}

class LoginRoute extends _i1.PageRouteInfo {
  const LoginRoute() : super(name, path: '/Login');

  static const String name = 'LoginRoute';
}

class OnBoardingRoute extends _i1.PageRouteInfo {
  const OnBoardingRoute() : super(name, path: '/on-boarding');

  static const String name = 'OnBoardingRoute';
}

class MyOrdersRoute extends _i1.PageRouteInfo {
  const MyOrdersRoute() : super(name, path: '/my-orders');

  static const String name = 'MyOrdersRoute';
}

class TrackOrderRoute extends _i1.PageRouteInfo<TrackOrderRouteArgs> {
  TrackOrderRoute({_i2.Key key, _i33.Order order})
      : super(name,
            path: '/track-order',
            args: TrackOrderRouteArgs(key: key, order: order));

  static const String name = 'TrackOrderRoute';
}

class TrackOrderRouteArgs {
  const TrackOrderRouteArgs({this.key, this.order});

  final _i2.Key key;

  final _i33.Order order;
}

class HomeRoute extends _i1.PageRouteInfo {
  const HomeRoute() : super(name, path: '/Home');

  static const String name = 'HomeRoute';
}

class FavoritesRoute extends _i1.PageRouteInfo {
  const FavoritesRoute() : super(name, path: '/Favorites');

  static const String name = 'FavoritesRoute';
}

class CartRoute extends _i1.PageRouteInfo {
  const CartRoute() : super(name, path: '/Cart');

  static const String name = 'CartRoute';
}

class ProfileRoute extends _i1.PageRouteInfo {
  const ProfileRoute() : super(name, path: '/Profile');

  static const String name = 'ProfileRoute';
}

class EditProfileRoute extends _i1.PageRouteInfo {
  const EditProfileRoute() : super(name, path: '/edit-profile');

  static const String name = 'EditProfileRoute';
}

class CardsScreenRoute extends _i1.PageRouteInfo {
  const CardsScreenRoute() : super(name, path: '/cards-screen');

  static const String name = 'CardsScreenRoute';
}

class ContactScreenRoute extends _i1.PageRouteInfo {
  const ContactScreenRoute() : super(name, path: '/contact-screen');

  static const String name = 'ContactScreenRoute';
}

class ChangePasswordRoute extends _i1.PageRouteInfo {
  const ChangePasswordRoute() : super(name, path: '/change-password');

  static const String name = 'ChangePasswordRoute';
}

class AccountSettingsRoute extends _i1.PageRouteInfo {
  const AccountSettingsRoute() : super(name, path: '/account-settings');

  static const String name = 'AccountSettingsRoute';
}

class AddressScreenRoute extends _i1.PageRouteInfo<AddressScreenRouteArgs> {
  AddressScreenRoute({_i2.Key key, bool isShipping})
      : super(name,
            path: '/address-screen',
            args: AddressScreenRouteArgs(key: key, isShipping: isShipping));

  static const String name = 'AddressScreenRoute';
}

class AddressScreenRouteArgs {
  const AddressScreenRouteArgs({this.key, this.isShipping});

  final _i2.Key key;

  final bool isShipping;
}

class AddAddressRoute extends _i1.PageRouteInfo {
  const AddAddressRoute() : super(name, path: '/add-address');

  static const String name = 'AddAddressRoute';
}

class AddNewCardScreenRoute extends _i1.PageRouteInfo {
  const AddNewCardScreenRoute() : super(name, path: '/add-new-card-screen');

  static const String name = 'AddNewCardScreenRoute';
}

class CategorisedProductsRoute
    extends _i1.PageRouteInfo<CategorisedProductsRouteArgs> {
  CategorisedProductsRoute(
      {_i2.Key key,
      _i34.WooProductCategory category,
      _i34.WooProductCategory searchCategory,
      List<_i34.WooProductCategory> childrenCategoryList = const []})
      : super(name,
            path: '/categorised-products',
            args: CategorisedProductsRouteArgs(
                key: key,
                category: category,
                searchCategory: searchCategory,
                childrenCategoryList: childrenCategoryList));

  static const String name = 'CategorisedProductsRoute';
}

class CategorisedProductsRouteArgs {
  const CategorisedProductsRouteArgs(
      {this.key,
      this.category,
      this.searchCategory,
      this.childrenCategoryList = const []});

  final _i2.Key key;

  final _i34.WooProductCategory category;

  final _i34.WooProductCategory searchCategory;

  final List<_i34.WooProductCategory> childrenCategoryList;
}

class SearchScreenRoute extends _i1.PageRouteInfo {
  const SearchScreenRoute() : super(name, path: '/search-screen');

  static const String name = 'SearchScreenRoute';
}

class AllProductsRoute extends _i1.PageRouteInfo<AllProductsRouteArgs> {
  AllProductsRoute(
      {_i2.Key key, _i35.HomeSectionDataHolder homeSectionDataHolder})
      : super(name,
            path: '/all-products',
            args: AllProductsRouteArgs(
                key: key, homeSectionDataHolder: homeSectionDataHolder));

  static const String name = 'AllProductsRoute';
}

class AllProductsRouteArgs {
  const AllProductsRouteArgs({this.key, this.homeSectionDataHolder});

  final _i2.Key key;

  final _i35.HomeSectionDataHolder homeSectionDataHolder;
}

class SettingsRoute extends _i1.PageRouteInfo {
  const SettingsRoute() : super(name, path: '/Settings');

  static const String name = 'SettingsRoute';
}

class PointsScreenRoute extends _i1.PageRouteInfo {
  const PointsScreenRoute() : super(name, path: '/points-screen');

  static const String name = 'PointsScreenRoute';
}

class LoginFromXRoute extends _i1.PageRouteInfo<LoginFromXRouteArgs> {
  LoginFromXRoute(
      {_i2.Key key, _i36.LoginFrom loginFrom = _i36.LoginFrom.undefined})
      : super(name,
            path: '/login-from-x',
            args: LoginFromXRouteArgs(key: key, loginFrom: loginFrom));

  static const String name = 'LoginFromXRoute';
}

class LoginFromXRouteArgs {
  const LoginFromXRouteArgs(
      {this.key, this.loginFrom = _i36.LoginFrom.undefined});

  final _i2.Key key;

  final _i36.LoginFrom loginFrom;
}

class DownloadsScreenRoute extends _i1.PageRouteInfo {
  const DownloadsScreenRoute() : super(name, path: '/downloads-screen');

  static const String name = 'DownloadsScreenRoute';
}

class NotificationScreenRoute extends _i1.PageRouteInfo {
  const NotificationScreenRoute() : super(name, path: '/notification-screen');

  static const String name = 'NotificationScreenRoute';
}

class TagProductsRoute extends _i1.PageRouteInfo<TagProductsRouteArgs> {
  TagProductsRoute({_i2.Key key, _i34.WooProductTag tag})
      : super(name,
            path: '/tag-products',
            args: TagProductsRouteArgs(key: key, tag: tag));

  static const String name = 'TagProductsRoute';
}

class TagProductsRouteArgs {
  const TagProductsRouteArgs({this.key, this.tag});

  final _i2.Key key;

  final _i34.WooProductTag tag;
}

**Comment by AniketMalik** [comment]
This file is from version **1.14.0** or previous. Please download the VERSION **1.14.1** from codecanyon and use that

**Comment by sohamd99** [comment]
I'm really sorry. I forgot to close project and open project of updated file.
