### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#45]
Hi Aniket,

I just noticed that when i try to send push notification through cloud messaging, the text and the title work fine but the notification icon displayed on the tab bar is the default icon of woostore app.
Can you please tell me how i can change this to my own app icon in png format

Kind regards
ishan

**Comment by AniketMalik** [comment]
Please read the documentation: 
https://aniketmalik.github.io/woostore_pro_documentation/configure-application/change-app-icon#change-android-notification-icon
