### ISSUE TITLE
Checkout issue 

### ISSUE THREAD

**Issue by moodiradi** [AniketMalik/ecommerce-store-support#47]
Hello after i set the application everything is working perfectly but when i sign in with my account i add 2 products to cart then i click check out button, atfer it takes me to checkout page i go back to cart and remove one product that i dont want to buy when i click again checkout button i still see the product that i deleted from cart. Any help

**Comment by AniketMalik** [comment]
This is caused by the latest version of WooCommerce. Please downgrade your WooCommerce version to 4.9.3 until a patch is released.

Download link:
https://developer.woocommerce.com/releases/
