### ISSUE TITLE
Cannot See Appointment or Bookable Products

### ISSUE THREAD

**Issue by sohamd99** [AniketMalik/ecommerce-store-support#48]
Hello I can't see calendar to select appointment or bookable products. I'm therefore unable to add products in cart and place order.

Please let me know how to add those products.

Thank You.

**Comment by AniketMalik** [comment]
The application currently supports simple, variable and external/affiliate products. 
Please let me know which plugin do you use for appointment or bookable products.

**Comment by sohamd99** [comment]
Woocommerce Appointments - By Bookingwp

https://bookingwp.com/

If you want I can give you plugin too. But I want this feature otherwise this app would be useless for me.

Please try your best.

**Comment by AniketMalik** [comment]
Sir, I am extremely occupied with integrating other pending features in the
application currently.

However I'll add this to the requested feature pipeline but I cannot give
you a timeline as to when the application will implement this feature.

If you want I can do a custom job for you to integrate this feature in the
application however it will be charged based on the complexity of the work
required to implement the feature in the application.

Please let me know your thoughts.

Thank you.

**Comment by sohamd99** [comment]
How much will you charge?

Also if it's gonna take more than 4 days then I'm not interested in this application and would demand for refund.

**Comment by AniketMalik** [comment]
Sir, it would take more than that specified time. 

Refund:
As per envato's policies a refund can be initiated if you have not downloaded the source code. As you've already downloaded the source code a refund cannot be initiated.

Also the description of the application listing page clearly states the features that are supported by the application.

**Comment by sohamd99** [comment]
So I have just wasted my money by purchasing this.

Thanks a lot.

*Appointment/Bookable products is a most important feature for multivendors

**Comment by AniketMalik** [comment]
Sir, all the information about the application is mentioned on the description for users to read through and make purchasing decision accordingly.

Will definitely add this feature in the future.

**Comment by sohamd99** [comment]
Any chance to see this function in a week or two?

**Comment by AniketMalik** [comment]
Unfortunately no. 
A lot of feature integrations are already pending which are already in development.
But these features will definitely be added in the future.

**Comment by sohamd99** [comment]
Can this feature be implemented in a month?
