### ISSUE TITLE
Help with Git version 

### ISSUE THREAD

**Issue by Sendibad** [AniketMalik/ecommerce-store-support#50]
I need help with git to update the application to new version without removing any edited code done by me any help or tutorial how to that i searched so much on the internet no results.

**Comment by AniketMalik** [comment]
Unfortunately there is not a simple answer to this. You will need to learn to merge the files from the older version with the newer version.

Please check out this article to see the GUI tools to compare and merge the files:
https://dzone.com/articles/7-code-merge-tools-to-make-your-life-7x-easier
