### ISSUE TITLE
Bash tools, no such file

### ISSUE THREAD

**Issue by Lastson4sure** [AniketMalik/ecommerce-store-support#51]
Good day, thanks for your previous response. 
After installing git bash for windows and right clicking  woostore pro and opening Git bash here, I input bash tools/create-keystore.sh, it returns "No such file or directory " please help.

**Comment by AniketMalik** [comment]
Please share the screenshot of the same.

**Comment by AniketMalik** [comment]
Sir, You are opening the terminal on the download package.
You need to open the **woostore_pro** directory which is inside the `download package / mobile-application / woostore_pro`.

I hope you understand this.

**Comment by Lastson4sure** [comment]
Thank you for your previous response. 
![IMG-20211006-WA0000](https://user-images.githubusercontent.com/91909803/136273138-ad05c195-05ec-4afe-b7cb-2f336a833488.jpg)
It says command not found in trying to create keystore

**Comment by Lastson4sure** [comment]
Good day, I had created the debug keystore but it asking for the password, I input the password I had used but it says incorrect,  I think I might have made mistakes other places I wouldn't know, is it possible to delete the project and start from scratch,  please give me guide to completely delete it and start a fresh.

**Comment by AniketMalik** [comment]
The issues that you see in the androidmanifest.xml file are ide related and will not effect the build process.

Did you change anything in the androidmanifest.xml file manually ?

**Comment by Lastson4sure** [comment]
No I did not change anything in it.

**Comment by Lastson4sure** [comment]
Yes but I skipped the configure app section, I felt I should leave the categories, colors screens etc to default, I'd come back to it later. I would have done all that if the emulator was showing me the app in real time, be it isn't instead it shows this error
![IMG-20211007-WA0001](https://user-images.githubusercontent.com/91909803/136618586-93f90d3c-d282-434e-abd2-74c99e672c2e.jpg)

**Comment by Lastson4sure** [comment]
Is androidx and gradle the same, I tried to migrate to androidx by clicking on Refactor/migrate to androidx, it say "no usages found. Please help
![IMG-20211008-WA0005](https://user-images.githubusercontent.com/91909803/136626891-23e0ce1e-5fcf-4aae-a4de-8b32a0be14e9.jpg)

**Comment by AniketMalik** [comment]
The application has already been migrated to androidx. 

Did you try the solutions from the previous link and build the application ?

**Comment by Lastson4sure** [comment]
Yes, I also tried sync project with gradle, I'm still stock up here. Is it not possible to delete the project and start over with a different Google account.
![IMG-20211010-WA0000](https://user-images.githubusercontent.com/91909803/136707731-6d2fc3e7-110b-414c-b2e3-7ed835b070f8.jpg)

**Comment by Lastson4sure** [comment]
I've been on it all this while, searching the internet and watching videos still no solution.

**Comment by AniketMalik** [comment]
Sir it seems that somehow your android project has corrupted. 

Please make a copy of the Woostore pro application and restart the process as it would be easier and much faster than finding the root cause of the underlying issue.

**Comment by Lastson4sure** [comment]
How do I make a copy please

**Comment by AniketMalik** [comment]
You will need to restart the process. Copy and paste the folder **mobile-application** and restart the setup of mobile app again.
