### ISSUE TITLE
Cart Error

### ISSUE THREAD

**Issue by ivanyiga** [AniketMalik/ecommerce-store-support#55]
Hello, I am facing an issue with the cart.. Whenever I log into an existing wordpress account on the app, The cart tells me to logout and login again. And when i click buy now it brings an error **“There has been a critical error on this website”**. Please help out

Woostore Pro version:  2.0.1
Woostore Pro API Version 3.0.0
WordPress Version: 5.8.

SCREENSHOT:
![device-2021-11-09-085325](https://user-images.githubusercontent.com/67748703/140870092-163b81ec-c56b-436f-9b02-c5790d75e6a4.png)
1

**Comment by AniketMalik** [comment]
Your website has been affected by some plugin due to incorrect installation. 

I recommend that you check the status of your website, take a backup and reinstall wordpress.
