### ISSUE TITLE
SIPPING OPTIONS DISAPPEARED

### ISSUE THREAD

**Issue by ivanyiga** [AniketMalik/ecommerce-store-support#56]
All over a sudden, shipping options have disappeared. I think it came after updating the woostore pro api plugin

**Comment by AniketMalik** [comment]
Which version are you using and which were you using previously ?

**Comment by ivanyiga** [comment]
I was using Version 3.0.0 then i updated to Version 3.1.0

**Comment by AniketMalik** [comment]
WooStore Pro Api version 3.1.0 is to be used with the mobile application version 2.1.0 as the API was changed to get all the shipping methods based on the cart items and the shipping address.
