### ISSUE TITLE
Issue: Token error checkout

### ISSUE THREAD

**Issue by footprintclub** [AniketMalik/ecommerce-store-support#61]
![image](https://user-images.githubusercontent.com/98261787/150686088-2d0db995-a3c7-439e-b2e8-cf29b06fa4bd.png)
Some customers receive this error message at checkout.

**Comment by AniketMalik** [comment]
This states that your JWT token has been expired and the user needs to
login again.

**Comment by footprintclub** [comment]
OK Thank you.  Can you add a user-friendly error message in a future release?

**Comment by AniketMalik** [comment]
Yes, the work on this has already been done and shall be released soon.
