### ISSUE TITLE
please solve

### ISSUE THREAD

**Issue by abhikashbabu** [AniketMalik/ecommerce-store-support#62]
C:\src\flutter\bin\flutter.bat --no-color build apk

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Running Gradle task 'assembleRelease'...                        
"ar": 5 untranslated message(s).
"de": 5 untranslated message(s).
"es": 5 untranslated message(s).
"fr": 5 untranslated message(s).
"hi": 5 untranslated message(s).
"id": 5 untranslated message(s).
"ja": 5 untranslated message(s).
"ko": 5 untranslated message(s).
"ru": 5 untranslated message(s).
"vi": 5 untranslated message(s).
"zh": 5 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 

This will generate a JSON format file containing all messages that 
need to be translated.
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13m 1s
Running Gradle task 'assembleRelease'...                          786.0s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by abhikashbabu** [comment]
![Uploading Cnbhjhjhghhgapture.PNG…]()

**Comment by AniketMalik** [comment]
Please delete this directory:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2

and then try to build the application
