### ISSUE TITLE
Woostore app register by phone problem 

### ISSUE THREAD

**Issue by abhikashbabu** [AniketMalik/ecommerce-store-support#63]
your app register phone was not working in it, it used to come otp but the otp section is not coming

**Comment by abhikashbabu** [comment]
Image https://photos.app.goo.gl/yCi8f1NJnswq5uDC8

**Comment by AniketMalik** [comment]
Please try the following:

In the file login_screen.dart inside the lib/screens/login/otp_login/widgets directory and remove the line at number 163

autoRetrievedSmsCodeForTesting: '123456',

**Comment by abhikashbabu** [comment]
the request is missing a vail app identifier meaning that neither Safetynet Check nor recaptca checks scueed error
