### ISSUE TITLE
This request is missing a valid app identifier, meaning that neither safetyNet checks nor reCAPTCHA checks succeeded

### ISSUE THREAD

**Issue by abhikashbabu** [AniketMalik/ecommerce-store-support#66]
Already implement seftynet , androidx.browser dependency and google cloud android device verification enable Still getting error my whatsapp no ​​8707360502
This request is missing a valid app identifier, meaning that neither safetyNet checks nor reCAPTCHA checks succeeded

**Comment by AniketMalik** [comment]
Please explain further when does this occur ?

**Comment by abhikashbabu** [comment]
This request is missing a valid app identifier, meaning that neither safetyNet checks nor reCAPTCHA checks succeeded

**Comment by abhikashbabu** [comment]
How to solve this error

**Comment by AniketMalik** [comment]
Please let me know the steps to reproduce this issue.

This could be related to a number of settings problem. For example the main issue seems to be with your Firebase Google Services file where your app's bundle id is different from the one present in that file.
