### ISSUE TITLE
How to Disable Shipping Option

### ISSUE THREAD

**Issue by Tony-Akani** [AniketMalik/ecommerce-store-support#67]
Hello,
Please i would like to disable shipping, because i only sell software in my store. 

Thanks

**Comment by AniketMalik** [comment]
Do you want to hide the "Track button" ?

**Comment by Tony-Akani** [comment]
There is a page on the checkout when you are trying to checkout that shows shipping option, and i do not have any shipping options, can i disable this?

**Comment by Tony-Akani** [comment]
I would also like to disable the tracking too

**Comment by AniketMalik** [comment]
As of now you can create a free shipping option in your WooCommerce store
so that the workflow for the payment isn't interrupted. I'll send you a
solution for your requirement soon.

Thank you for your patience.

**Comment by Tony-Akani** [comment]
Okay, But can i ask how long it would take to get this solution, so that i can pause my dev

**Comment by AniketMalik** [comment]
The functionality you are looking forward for changes the core
functionality of the WooCommerce checkout process which could take about
2-4 days to propose a solution which does not break the application's
functionality. I hope you understand.

**Comment by Tony-Akani** [comment]
I do understand brother as i am a dev myself, thank you for the honest and quick response. 
I am looking forward to a solution. If possible you can make it set the free option to default, and skip the page. Looking forward to your solution in your time then.

**Comment by AniketMalik** [comment]
Hello, Please try the following patch to see if the functionality works for you.

Please comment out or remove the following code on line number 53 in the file lib/screens/cart/checkout/checkout_native.dart

```dart
ShippingMethods(),
```

**Comment by Tony-Akani** [comment]
Okay, Let me try it

**Comment by Tony-Akani** [comment]
Yes this works great with no issues, I will use this, But one more question. If i do disable the Billing and shipping methods, will this automatically set everything to NULL, and proceed as well?

**Comment by AniketMalik** [comment]
The information is not set the NULL instead empty strings and 0 ( int ) are
used where ever required by WooCommerce.
However i advice you to not disable the shipping and billing methods as
this may break the WooCommerce functionality.

**Comment by Tony-Akani** [comment]
Okay, I understand, If the User had already bought a product from the website, does the App automatically populates the billing and shipping fields, with the ones used previously?

**Comment by AniketMalik** [comment]
Yes, the order object is fetched from the website which has the billing and shipping information and that is used to display the order details.
