### ISSUE TITLE
Incompatibility problem with the CoCart - Get Cart Enhanced with woocommerce 4.2.0

### ISSUE THREAD

**Issue by PMCONSULTINGSAP** [AniketMalik/ecommerce-store-support#7]
Good morning, I have an incompatibility problem with the CoCart - Get Cart Enhanced (By Sébastien Dumont) (Required) which blocks the installation progress. Attached photo of current versions.

If you require additional information, contact us to try to collect everything you need.

I would appreciate a solution with the current configuration of the store, since it is not possible to update for business continuity.

![Screenshot_1](https://user-images.githubusercontent.com/83362470/116438634-4081e900-a814-11eb-8e61-cfcc353389f6.png)

**Comment by AniketMalik** [comment]
You are using a very old version of WooCommerce plugin in your website.
Unfortunately I could not find compatible version of CoCart which can work with WooCommerce 4.2.0.
However I will keep looking for a solution if you really cannot upgrade.

I recommend you to upgrade the version as newer versions bring in many bug fixes and code enhancements.

**Comment by PMCONSULTINGSAP** [comment]
When buying it, a minimum version of woocommerce was not indicated, other options work with version 3 onwards, backward compatibility is important. On the other hand, it is important to find a solution to the current version since it is not possible to make any changes in the production server that is being continuously consulted by clients. Security measures are carried out by the IT area. We hope you can provide us with a solution.

**Comment by AniketMalik** [comment]
Please allow me some time to find a solution. Will definitely work something out.

**Comment by PMCONSULTINGSAP** [comment]
Okay, stay tuned.

 We appreciate the extra effort.

**Comment by AniketMalik** [comment]
I've been tested positive for covid yesterday as I had high fever. Please allow me a recovery time of 7-10 days to gain my health back and I'll look for your solution.

I hope you understand.

**Comment by PMCONSULTINGSAP** [comment]
Sorry to hear it. The subject of health is important. If we would like to know what your diagnosis is and possible feasible solutions that you can implement.

Note: We have the impression (you can validate it) that a feasible and quick solution would be to use a less recent version of co cart, and an older version of woostore app, even if it costs the latest features. This as a temporary solution.

You comment to us.
Thank you

**Comment by AniketMalik** [comment]
I have talked to the author of the plugin if a version is available which works with woocommerce 4.2.0 and unfortunately their isn't any. 

WooStore Pro has been using cocart enhanced from the very first version so there isn't any version which doesn't have it.

Unfortunately you'll either have to upgrade to use the plugin. A rest api for cart will be created within WooStore Pro Api plugin itself in the future but again it will also not be compatible with this older version of woocommerce.

**Comment by PMCONSULTINGSAP** [comment]
You will see I was reviewing the topic and I found the source of co cart, considering that our installation is from July 2020, I find that yes, positively, it has a version of coo-cart compatible with woocommerce 4.2.x. So what is the problem in using it? Take it into account and tell me your opinion. 

link: https://github.com/co-cart/co-cart/releases?after=v2.1.3



![FireShot Capture 056 - Releases · co-cart_co-cart - github com](https://user-images.githubusercontent.com/83362470/116553898-387f8300-a8c0-11eb-8a94-126872ed58e6.png)

**Comment by AniketMalik** [comment]
You have a problem with CoCart Get Cart Enhanced Plugin and this release list is for the CoCart plugin. They both are different plugins but created by the same author.

**Comment by PMCONSULTINGSAP** [comment]
As far as you can see, they both start from the same core of functionalities, bring woocommerce products mainly, they must share similar interfaces and classes, not to mention that since they are almost the same by the same author, is not this enough to solve the problem?

**Comment by AniketMalik** [comment]
I suppose this won't work. However you can try to use it with your installation.

**Comment by PMCONSULTINGSAP** [comment]
Excuse? Better leave the sarcasm, if I suggest it is for you to evaluate not to receive sarcasm and less childish comments.

Well I see, you won't do anything to solve the problem. I thought that when buying a product through envato / codecayon there was a guarantee of premium service and support, but I notice that not all programmers take their work seriously. You should have added compatibility like everyone else does, not just wait for people to buy and these issues arise.

**Comment by AniketMalik** [comment]
Apologies to have offended you. I did not mean in any sense to make a harsh comment.

All I meant was that please go ahead and try the plugin. Meanwhile I am looking into other solutions.

**Comment by PMCONSULTINGSAP** [comment]
I hope you send us the solution of the case as soon as possible.

**Comment by AniketMalik** [comment]
Please checkout the following release if it is compatible with your version of WooCommerce installation.
https://github.com/co-cart/cocart-get-cart-enhanced/releases/tag/v1.9.2

The source of this link is the following:
https://github.com/co-cart/cocart-get-cart-enhanced/releases

There are other releases as well. Currently I am looking into each release for compatibility with woocommerce 4.2.0. Till then please try and install the version from above.

Thank you. Please keep me posted if you see an error

**Comment by PMCONSULTINGSAP** [comment]
Ok, I will request access to the dev server which is a clone of the production server to validate the compatibility. It may take me a while, but having it I inform you, to move forward.

**Comment by PMCONSULTINGSAP** [comment]
This version of the plugin was installed and activated successfully.
https://github.com/co-cart/cocart-get-cart-enhanced/releases/tag/v1.9.2

**Comment by PMCONSULTINGSAP** [comment]
Excuse me, why have you closed the ticket?
Until now we wait for the solution to the problem. Do you plan to drop it? He never sent us the list of the correct plugins for the solution.

So far we are having a very bad support experience.

**Comment by AniketMalik** [comment]
Sir, I saw the comment that you were successfully able to install https://github.com/co-cart/cocart-get-cart-enhanced/releases/tag/v1.9.2 this version of the plugin which is why I closed this issue. 

If you still have any issues please let me know I'll reopen it.

**Comment by PMCONSULTINGSAP** [comment]
This is the complete list of plugins, send us the list with the correct versions for woocommerce 4.2. GIVE US A COMPLETE SOLUTION, we don't have to write to you every time. Take your job seriously.


![image](https://user-images.githubusercontent.com/83362470/116790743-8a203d00-aa7b-11eb-8ca5-4986636d7b17.png)

**Comment by AniketMalik** [comment]
Sir, the only plugins which depend on WooCommerce for their functionality are 

1. Cart Rest Api for WooCommerce
2. Co Cart Get cart enhanced
3. Advanced shippment tracking for WooCommerce.

All other plugins which start with the name WooCommerce are optional like WooCommerce Paypal checkout, etc.

All other mentioned plugins does not depend on WooCommerce so the WooCommerce version doesn't affect them. You can install the latest version of these plugins without any issues.

Now please answer the following questions:

1. Have you installed all these plugins in your WordPress site ?
2. Which all plugins were you not able to install properly or caused an issue while installing or activating them ?
3. Only CoCart get cart enhanced plugin caused the compatibility issue but was resolved when you installed the version 1.9.2 ?
4. Did you run the application on your local device and test the integration after installing all the plugins ? If yes did you encounter any errors in the mobile application ?

Please answer all the above mentioned questions will full details.
