### ISSUE TITLE
Error configuring android app

### ISSUE THREAD

**Issue by PMCONSULTINGSAP** [AniketMalik/ecommerce-store-support#8]
Error configuring android app

Still waiting for the correct combination of packages from the previous problem.

I went on to configure the app, meanwhile, but when running it in android studio after pub get and doctor flutter it throws me this error:

![image](https://user-images.githubusercontent.com/83362470/116650280-88a12880-a946-11eb-9427-31eac0e6dd41.png)

Launching lib \ main.dart on Android SDK built for x86 in debug mode ...
Running Gradle task 'assembleDebug' ...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ': apple_sign_in: parseDebugLibraryResources'.
> Could not resolve all files for configuration ': apple_sign_in: androidApis'.
   > Failed to transform file 'android.jar' to match attributes {artifactType = android-platform-attr, org.gradle.libraryelements = jar, org.gradle.usage = java-runtime}
      > Execution failed for PlatformAttrTransform: C: \ Users \ user \ AppData \ Local \ Android \ sdk \ platforms \ android-28 \ android.jar.
         > C: \ Users \ user \ AppData \ Local \ Android \ sdk \ platforms \ android-28 \ android.jar (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by AniketMalik** [comment]
Please run `flutter clean` from the root folder and then run `flutter pub get`.

**Comment by AniketMalik** [comment]
Also a better implementation of apple sign in is about to be released. Stay tuned for the same.

**Comment by AniketMalik** [comment]
The missing files error is due to the fact that the localization files have been cleaned when we ran flutter clean.
These can be generated without an issue after a successful build.

Please send me the version of the Android device you are trying to use to build the application.

Note:
A new implementation of the Apple sign in has been added to the application v1.5.2. It will be live soon. This update will remove the dependency on the apple_sign_in plugin which is causing issue for your build.

Please download the update from Codecanyon as it will be live in about 1 hour.

**Comment by PMCONSULTINGSAP** [comment]
After the clean, yes, the put get was applied.

I copy the configuration of the android sdk, to which I recently added the sdk 5, 7 and 9, 10 since it only worked with the 11. With the latter it stopped showing the 4 errors of the dart analysis - An advance :) -. the project settings have not been touched.

![image](https://user-images.githubusercontent.com/83362470/116726392-d0f13280-a9a8-11eb-93ba-0c6f89bc8d13.png)






But the apple sign, if it is necessary to update since the error persists, I copy log, I will be aware to download the latest version.

-- log --
Launching lib\main.dart on Samsung in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apple_sign_in:parseDebugLibraryResources'.
> Could not resolve all files for configuration ':apple_sign_in:androidApis'.
   > Failed to transform file 'android.jar' to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}
      > Execution failed for PlatformAttrTransform: C:\Users\user\AppData\Local\Android\sdk\platforms\android-28\android.jar.
         > C:\Users\user\AppData\Local\Android\sdk\platforms\android-28\android.jar (El sistema no puede encontrar el archivo especificado)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by AniketMalik** [comment]
Thanks for the positive response.

The new version v1.5.2 removes this apple sign in dependency and introduce a new one which might resolve the issue you are facing with this one.
