### ISSUE TITLE
I only have the public ip 0.0.0.0 of server development with internet access, but I see that there are problems

### ISSUE THREAD

**Issue by PMCONSULTINGSAP** [AniketMalik/ecommerce-store-support#9]
On the other hand, leaving only the main thing outside of login, points of woocommerce, firebase, etc ... I am configuring the wooconfig.dart and it asks me for a domain, however as I told you I am working on a test server, instead of passing it the www domain. .. from the web I only have the public ip 0.0.0.0 of development with internet access, but I see that there are problems. How can I solve this? I hope as much detail as possible.   

---- I copy the log ----

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:59281/6UzbnwC6gXo=/ws
Syncing files to device AOSP on IA Emulator...
I/Choreographer(13678): Skipped 104 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(13678): eglMakeCurrent: 0xe8786ee0: ver 2 0 (tinfo 0xcff6f460)
I/OpenGLRenderer(13678): Davey! duration=3001ms; Flags=1, IntendedVsync=7954607650375, Vsync=7956340983639, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=7956347798600, AnimationStart=7956347876000, PerformTraversalsStart=7956349661600, DrawStart=7957536876200, SyncQueued=7957537998400, SyncStart=7957538916000, IssueDrawCommandsStart=7957539107400, SwapBuffers=7957556345100, FrameCompleted=7957610390300, DequeueBufferDuration=11308000, QueueBufferDuration=525000, 
D/EGL_emulation(13678): eglMakeCurrent: 0xe6f16080: ver 2 0 (tinfo 0xcfea1800)
D/eglCodecCommon(13678): setVertexArrayObject: set vao to 0 (0) 1 0
I/FLTFireBGExecutor(13678): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
D/eglCodecCommon(13678): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(13678): eglCreateContext: 0xe6f17040: maj 2 min 0 rcv 2
D/eglCodecCommon(13678): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(13678): eglCreateContext: 0xe6f170a0: maj 2 min 0 rcv 2
D/HostConnection(13678): HostConnection::get() New Host Connection established 0xcff40500, tid 13793
D/HostConnection(13678): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
D/EGL_emulation(13678): eglMakeCurrent: 0xe6f170a0: ver 2 0 (tinfo 0xc3320510)
I/FLTFireMsgService(13678): FlutterFirebaseMessagingBackgroundService started!
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Running ==> isCustomerLoggedIn ==> AuthController ==> authController.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl(13678): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl(13678): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Running ==> _init ==> CoCart ==> coCart.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl(13678): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Setting key: null
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Setting cookie: null
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 End ==> _init ==> CoCart ==> coCart.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl(13678): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Is Logged in - false
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 End ==> isCustomerLoggedIn ==> AuthController ==> authController.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (13678): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:auto_route/src/router/controller/routing_controller.dart': Failed assertion: line 456 pos 12: '_pages.isNotEmpty': is not true.
E/flutter (13678): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (13678): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (13678): #2      BranchEntry.replace (package:auto_route/src/router/controller/routing_controller.dart:456:12)
E/flutter (13678): #3      RootStackRouter.replace (package:auto_route/src/router/root_stack_router.dart:152:20)
E/flutter (13678): #4      _SplashScreenState._handleAnimationStatus (package:woostore_pro/screens/splash/splash.dart:130:40)
E/flutter (13678): <asynchronous suspension>
E/flutter (13678): 
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 [ Initiating for CategoriesProvider ] initState ==> ViewStateController ==> viewStateController.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 [ Initiating Type: HomeViewModel ] initState ==> SliverViewStateController ==> viewStateController.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Running ==> getCart ==> CartProvider ==> cartProvider.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Running ==> getCategories ==> TestWooService ==> Woocommerce.service
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl(13678): Read: key not present => Skip ensureInitStorageCipher and return null
D/FlutterSecureStoragePl(13678): Read: key not present => Skip ensureInitStorageCipher and return null
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 Running ==> fetchSections ==> HomeViewModel ==> homeViewModel.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):    INFO ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):    INFO │ 💡 Got data with length: 0
I/flutter (13678):    INFO └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   DEBUG │ 🐛 End ==> fetchSections ==> HomeViewModel ==> homeViewModel.dart
I/flutter (13678):   DEBUG └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   ERROR │ Exception: WooCommerce Error!
I/flutter (13678):   ERROR │ code: woocommerce_rest_authentication_error
I/flutter (13678):   ERROR │ message: Firma no válida - la firma proporcionada no coincide.
I/flutter (13678):   ERROR │ status: 401
I/flutter (13678):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13678):   ERROR │ #0   WooCommerce._handleHttpError (package:woocommerce/woocommerce.dart:2106:9)
I/flutter (13678):   ERROR │ #1   WooCommerce.get (package:woocommerce/woocommerce.dart:2191:7)
I/flutter (13678):   ERROR │ #2   <asynchronous suspension>
I/flutter (13678):   ERROR │ #3   WooCommerce.getProductCategories (package:woocommerce/woocommerce.dart:1023:22)
I/flutter (13678):   ERROR │ #4   <asynchronous suspension>
I/flutter (13678):   ERROR │ #5   WooService.getCategories (package:woostore_pro/services/woocommerce/woocommerce.service.dart:136:11)
I/flutter (13678):   ERROR │ #6   <asynchronous suspension>
I/flutter (13678):   ERROR │ #7   CategoriesProvider.getCategories (package:woostore_pro/screens/categories/viewModel/categories.provider.dart:49:11)
I/flutter (13678):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13678):   ERROR │ ⛔ Get categories error
I/flutter (13678):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   ERROR ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13678):   ERROR │ CoCartException{code: 404, status: rest_no_route, message: No se ha encontrado la ruta que coincida con la URL y el método de la solicitud}
I/flutter (13678):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13678):   ERROR │ ⛔ Get Cart CoCartException
I/flutter (13678):   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by AniketMalik** [comment]
Please remove the "/" at the end of your IP address
For example change from this

http://192.168.0.102/ 

to this

http://192.168.0.102

**Comment by AniketMalik** [comment]
Were you able to resolve the problems after changing the IP address from the solution above ?
